/**
 * PKG-00 — the inner circle and the family (bible §4.1, §4.2).
 *
 * Affinity rules (§4.7): inner circle decays 1/week when neglected, family 0.5/week (engine-applied
 * via `decay`). Baselines feed the mirror's normalized selector: jax 40, byteme 25, mira 20.
 * `name` is how the player knows the person (used as the dialog speaker label and by `{npc:id}`);
 * `handle` is their pager/forum nick (`{nick:id}`).
 */
import { defineContent } from '@/engine/registry'

export default defineContent({
  npcs: [
    // ── Inner circle ──────────────────────────────────────────────────────────
    {
      id: 'jax',
      name: 'Jax',
      handle: 'JaxAttack',
      faction: 'fac.loft',
      role: 'Best friend, since sixth grade',
      avatar: 'JX',
      color: '#c0392b',
      social: true,
      startsMet: true,
      startAffinity: 40,
      decay: 1,
      baseline: 40,
      bio: [
        'Jacob Ferreira, universally Jax. Your best friend since sixth grade, when he traded you half a Walkman for a whole bike and you both walked away sure you had won. Funnier than he is careful, louder than he is sure, and loyal in a way that is going to get him hurt one day.',
        'He can talk his way into places you would have to work very hard to get into. It scares him how good he is at it, so mostly he uses it to get free refills.',
        'He lives with his mom and his little sister Rosa at the far end of the Row. Whatever Jax is doing, some part of it is for Rosa.',
        { if: { flag: 'a1.jax_covered_you' }, text: 'When you bricked your first crack in front of the whole board, Jax turned it into a joke and took the mockery himself. He has never once brought it up.' },
        { if: { flag: 'a1.bond_jax' }, text: 'Some friendships are just habit. This one you kept on purpose, and he knows it.' },
        { if: { flag: 'npc.jax.protected' }, text: 'You finished the job that was going to sink him. He hasn\'t found a way to say thank you that doesn\'t make you both uncomfortable, so he just shows up with pizza.' },
        { if: { flag: 'npc.jax.aborted' }, text: 'You talked him out of the hot contract. It was the right call. Rosa\'s bills didn\'t care.' },
        { if: { flag: 'npc.jax.covered' }, text: 'You fed the client something convincing and got him out clean. He still doesn\'t know how close it was.' },
        { if: { flag: 'npc.jax.alone' }, text: 'The night he called you at 3 a.m., you let him handle it alone. He did, sort of. He calls less now.' },
        { if: { flag: 'npc.jax.exposed' }, text: 'The client got spooked. Somewhere a file has Jax\'s name in it, and he knows it. He checks the street before he gets out of the car.' },
        { if: { flag: 'a2.took_jax_fall' }, text: 'You took the fall for him at the raid. Ten days in a cell. He says he will owe you forever, and he intends to pay in pizza.' },
        { if: { npc: 'jax', fate: 'arrested' }, text: 'Arrested. His mother keeps his room exactly as it was. The Cathode booth you two used still has his initials carved under the table.' },
        { if: { npc: 'jax', fate: 'flipped' }, text: 'He flipped to save himself. He wears it like a cast on a broken arm: everyone can see it, and nobody asks.' },
        { if: { npc: 'jax', fate: 'free' }, text: 'Free, and still Jax. He has started saying "be careful" when you leave, which is new, and which you hate.' },
        { if: { npc: 'jax', fate: 'backroom_partner' }, text: 'He runs the Cathode back room with you now: coffee hot, kids honest, door always open. Best job either of you ever had.' },
        { if: { npc: 'jax', fate: 'gone' }, text: 'He left. No big fight, just a slow drift, then a moving truck, then a postcard with nothing on it but a drawing of a very bad dog.' },
        { if: { npc: 'jax', fate: 'dead' }, text: 'Jax is dead. His pager number still works. You haven\'t called it. You haven\'t cancelled it either.' },
      ],
    },
    {
      id: 'priya',
      name: 'Priya Raman',
      handle: 'root_cause',
      faction: 'fac.halcyon',
      role: 'Mentor · senior engineer at Halcyon Systems',
      avatar: 'PR',
      color: '#6b4fa3',
      social: true,
      startAffinity: 10,
      decay: 1,
      baseline: 25,
      bio: [
        'Late thirties, reading glasses pushed up into her hair, a mug that says WORLD\'S OKAYEST ENGINEER. Priya Raman was a legend in the scene before you could spell your own handle. Then one day she went legit and took a job at Halcyon Systems, and nobody on the board has ever quite forgiven her.',
        'She teaches the way a good surgeon talks: short sentences, no wasted motion, the occasional terrifying joke. "Rule one: the machine is never the vulnerability. The person who bought the machine is the vulnerability. Rule two: you are a person who bought a machine."',
        { if: { flag: 'a2.priya_backstory' }, text: 'In \'99 she found something ugly inside a client: an early draft of what would become PARALLAX. She wrote it up. They bought the report, and her silence with it. She has been paying it back, a little at a time, ever since.' },
        { if: { flag: 'fac.halcyon.employed' }, text: 'She got you in the door at Halcyon and pretends she didn\'t.' },
        { if: { flag: 'npc.priya.warned_you' }, text: 'She cornered you at the Cathode once and told you exactly where your road ends. You are still deciding whether she was right.' },
        { if: { flag: 'npc.priya.debt' }, text: 'When Mom got sick, Priya fronted the money and wouldn\'t hear the word "loan." You both know it was a loan.' },
        { if: { npc: 'priya', fate: 'martyr' }, text: 'She told the truth, on the record, under her own name. The industry calls her difficult. The city calls her brave. She calls it overdue.' },
        { if: { npc: 'priya', fate: 'complicit' }, text: 'She stopped asking questions. She is good at her job and very well paid, and she no longer keeps the mug on her desk.' },
        { if: { npc: 'priya', fate: 'cofounder' }, text: 'You and Priya built something clean together. It\'s small, it pays everyone on time, and it doesn\'t sell anyone.' },
        { if: { npc: 'priya', fate: 'broken' }, text: 'She quit and left the city. Her last email to you was one line: "Rule two. Remember rule two."' },
        { if: { npc: 'priya', fate: 'saved' }, text: 'You took the fall so her name stayed clean. She never asked you to, and she has never forgiven you for it, which is how you know she loves you.' },
      ],
    },
    {
      id: 'corvid',
      name: 'Corvid',
      handle: 'Corvid',
      faction: 'fac.loft',
      role: 'Sysop of the Loft',
      avatar: 'CV',
      color: '#2c3e50',
      social: true,
      startAffinity: 10,
      decay: 1,
      baseline: 25,
      bio: [
        'The Loft\'s sysop since the BBS days: forties, a grey streak, a black coat in every season, and a voice that makes rooms go quiet without ever being raised. Nobody on the board remembers a time before Corvid, and the few who might aren\'t talking.',
        'She believes the scene is a commons: tools shared, knowledge given away, and nobody, ever, rats. When the cops came for Deadline in \'94, forty people wiped their drives the same night and not one of them said a word. She organized that night. She\'ll tell you it organized itself.',
        { if: { any: [{ flag: 'npc.corvid.trusts' }, { faction: 'fac.loft', gte: 50 }] }, text: 'Her legal name is Eleanor Voss. Maybe a dozen people alive know it. You\'re one of them now, and she is watching to see what you do with it.' },
        { if: { flag: 'npc.corvid.trusts' }, text: 'You brought her the thing you found on Ruth Alvarez\'s PC before you told anyone else. She hasn\'t forgotten.' },
        { if: { flag: 'npc.corvid.wary' }, text: 'You took the bait on her little test. She is still polite to you. That\'s worse.' },
        { if: { flag: 'a2.solidarity' }, text: 'When they came for her, you organized the solidarity wipe, just like \'94. She said "thank you" exactly once, and meant it more than anyone ever has.' },
        { if: { all: [{ flag: 'npc.corvid.charged' }, { npc: 'corvid', fate: 'normal' }] }, text: 'The raid left her facing charges. She keeps running the board as if nothing is wrong, which is how you know everything is.' },
        { if: { flag: 'fac.loft.side_switch' }, text: 'You backed Switch against her in the schism. She didn\'t argue. She just stopped saving you a seat.' },
        { if: { npc: 'corvid', fate: 'martyred' }, text: 'Eight years. Her last post before sentencing was two lines: "Keep the lights on. Don\'t sell the building."' },
        { if: { npc: 'corvid', fate: 'exile' }, text: 'Gone. The board went dark the night she left. Somewhere there is a server nobody can visit, and she is the only one with the key.' },
        { if: { npc: 'corvid', fate: 'bought' }, text: 'Aperture bought her. Nobody on the board says it out loud. They just stopped using her name.' },
        { if: { npc: 'corvid', fate: 'succeeded' }, text: 'She named you sysop and walked out clean, into a life with a garden in it. She sends seed catalogs with rude notes in the margins.' },
        { if: { npc: 'corvid', fate: 'vindicated' }, text: 'The scene rebuilt itself around her ethic, and she is back in the chair, pretending not to be pleased.' },
      ],
    },
    {
      id: 'mira',
      name: 'Mira Okonkwo',
      handle: 'nyx',
      faction: 'fac.loft',
      role: 'Rival · the cleanest hands on the board',
      avatar: 'NX',
      color: '#1f6f8b',
      social: true,
      romanceable: true,
      startAffinity: 15,
      decay: 1,
      baseline: 20,
      bio: [
        {
          if: { seen: 'a1_mira_dunk' },
          text: 'Mira Okonkwo, nyx on the board: your age, transferred in from Ridgeport, and better than you at almost everything in a way that is very hard to forgive. You brute-force it. She reads the source, finds the flaw, and has coffee.',
          else: 'nyx: a handle on the Loft board who dunked on your very first post and signed off with *hugz*, which somehow made it worse. You don\'t know who is behind it. You would very much like to.',
        },
        { if: { seen: 'a1_mira_dunk' }, text: 'She\'s quiet in rooms and devastating in text. She doesn\'t do crews. She doesn\'t do favors. She does, it turns out, keep the coffee warm.' },
        { if: { flag: 'npc.mira.respect' }, text: 'You asked her to teach you the trick instead of sulking. She pretended that didn\'t impress her.' },
        { if: { flag: 'npc.mira.rivalry' }, text: 'You challenged her right back. The two of you now race every board puzzle like it\'s the Olympics, and keep score in a shared text file neither of you admits exists.' },
        { if: { any: [{ flag: 'npc.mira.secret_hinted' }, { flag: 'npc.mira.trusts' }] }, text: 'Something happened in Ridgeport. She took a fall for someone she loved, and he made her disappear, scrubbing her name off everything they had built together. She doesn\'t talk about it. She doesn\'t have to.' },
        { if: { flag: 'npc.mira.trusts' }, text: 'She trusts you. She told you so exactly once, at 4 a.m., and then pretended the connection dropped.' },
        { if: { flag: 'npc.mira.betrayed' }, text: 'You sold her out. She hasn\'t said a word to you since, which, from Mira, is the loudest thing possible.' },
        { if: { npc: 'mira', romance: 'flirting' }, text: 'Something\'s there. Late-night pages that go on too long. Neither of you names it.' },
        { if: { npc: 'mira', romance: 'dating' }, text: 'You\'re seeing each other. She still beats you at every puzzle, but now she explains how afterwards.' },
        { if: { npc: 'mira', romance: 'partner' }, text: 'You live together. Two desks, one very tired router, and a fridge note that just says "*hugz* - buy milk".' },
        { if: { npc: 'mira', romance: 'engaged' }, text: 'Engaged. She planned the wedding in a spreadsheet, color-coded, with a tab for contingencies.' },
        { if: { npc: 'mira', romance: 'married' }, text: 'Married. She signs the grocery list *hugz*, and after all these years it still gets you.' },
        { if: { npc: 'mira', romance: 'ex' }, text: 'It ended. Some nights you still reach for the pager to send her the answer before she finds it.' },
        { if: { npc: 'mira', fate: 'gone' }, text: 'She left Port Lumen. No goodbye post, just a handle that stopped logging in.' },
        { if: { npc: 'mira', fate: 'rival' }, text: 'She works for Aperture now, against you, and she is very, very good at it.' },
        { if: { npc: 'mira', fate: 'casualty' }, text: 'Your plan went fast instead of right, and Mira paid for it. You think about that more than anything else you\'ve done.' },
        { if: { npc: 'mira', fate: 'flips_you' }, text: 'She handed you to the Bureau. You can\'t even say you didn\'t have it coming.' },
      ],
    },

    // ── Family ───────────────────────────────────────────────────────────────
    {
      id: 'mom',
      name: 'Mom',
      faction: 'fac.hood',
      role: 'Your mother · Linh Tan',
      avatar: 'M',
      color: '#b5651d',
      social: true,
      startsMet: true,
      startAffinity: 55,
      decay: 0.5,
      baseline: 50,
      bio: [
        'Linh Tan: bookkeeper at the cannery office for nineteen years, feeder of anyone who walks through her door, and the only person alive who can make "did you eat?" sound like a hug and an accusation at once.',
        '"I don\'t understand what you do. I understand you don\'t sleep, and you flinch when the phone rings. A mother can work with that."',
        { if: { all: [{ housing: 'parents_flat' }, { npc: 'mom', fateNot: ['passed', 'estranged'] }] }, text: 'She yells up the stairs to get off the phone line about six times a day. You\'ve learned to hear it through headphones.' },
        { if: { flag: 'life.family_shield' }, text: 'When the men in jackets came asking, she looked them in the eye and lied like a professional. She has never mentioned it since.' },
        { if: { npc: 'mom', fate: 'healthy' }, text: 'She got sick, and she got better. She walks the Row every morning now, doctor\'s orders, and reports back on everyone\'s business.' },
        { if: { npc: 'mom', fate: 'recovered_dark' }, text: 'She\'s alive because of money you would rather not explain. She has never asked where it came from. Sometimes you catch her looking at you like she\'s reading a letter in a language she used to know.' },
        { if: { npc: 'mom', fate: 'passed' }, text: 'Mom is gone. Her reading glasses are still on the kitchen windowsill. Nobody has moved them.' },
        { if: { npc: 'mom', fate: 'estranged' }, text: 'She doesn\'t call anymore. When you walk past the flat the curtain moves, and then it doesn\'t.' },
      ],
    },
    {
      id: 'dad',
      name: 'Dad',
      faction: 'fac.hood',
      role: 'Your father · Robert Tan',
      avatar: 'D',
      color: '#5d6d3a',
      social: true,
      startsMet: true,
      startAffinity: 45,
      decay: 0.5,
      baseline: 45,
      bio: [
        'Robert Tan kept the paper line running at the Port Lumen mill for twenty years. He has a toolbox for every occasion, a saying for every tool, and a flannel shirt for every day of the week.',
        '"My father fixed radios. I fixed the paper line. Long as one of us can fix something." He is proud of you in a way he can only express by asking whether you\'ve checked your oil.',
        { if: { flag: 'a1.dad_laid_off' }, text: 'The mill let him go in the autumn of 2001, along with two hundred others. He still gets up at 5:40 every morning. He just doesn\'t have anywhere to go.' },
        { if: { flag: 'side.dad_truth' }, text: 'You told him the layoffs were decided long before the "computer problem." He took it quietly, then fixed every squeaky hinge in the flat in a single afternoon.' },
        { if: { flag: 'side.dad_spared' }, text: 'You never told him what you found out about the layoffs. Some days that feels like kindness.' },
        { if: { all: [{ flag: 'npc.dad.mill_job' }, { npc: 'dad', fateNot: 'mill_ghost' }] }, text: 'He\'s working at the new data center now. At the mill. He says it\'s just a job.' },
        { if: { npc: 'dad', fate: 'retrained' }, text: 'You taught him PCs, and now half the Row calls him when their screen goes blue. He charges in casseroles.' },
        { if: { all: [{ npc: 'dad', fate: 'retrained' }, { flag: 'npc.dad.business' }] }, text: 'PC Doctor, booked solid. He had business cards printed and gives them to everyone, including you, twice.' },
        { if: { npc: 'dad', fate: 'mill_ghost' }, text: 'He took a job at the old mill, the data center now. He walks the same floor he used to, between machines that don\'t need him, making sure they stay cold.' },
        { if: { npc: 'dad', fate: 'spiral' }, text: 'He drinks now. Not loudly. He just gets smaller every time you see him.' },
        { if: { npc: 'dad', fate: 'dating_again' }, text: 'He\'s seeing someone. Her name is Bernadette, and she laughs at his jokes, which nobody has done in years.' },
      ],
    },
    {
      id: 'kim',
      name: 'Kim',
      handle: 'kimcognito',
      faction: 'fac.hood',
      role: 'Your little sister',
      avatar: 'K',
      color: '#c2185b',
      social: true,
      startsMet: true,
      startAffinity: 35,
      decay: 0.5,
      baseline: 35,
      bio: [
        {
          if: { day: true, lte: 1460 },
          text: 'Kim Tan, fourteen going on forty. Sharp enough to cut, sarcastic enough to bleed, and fully aware of which ICQ number you use for the other stuff.',
          else: 'Kim Tan, all grown up and still sharper than you. She stopped needing a burned CD for her silence years ago. Now she just gives you a look.',
        },
        '"You think I don\'t know what you do up there? I\'m not blind." She will sell her silence for a burned CD, and she raises the price every time you forget her birthday.',
        { if: { var: 'kim_trajectory', gte: 2 }, text: 'Lately she asks about colleges. Real ones, with brochures. She pretends it\'s for a friend.' },
        { if: { var: 'kim_trajectory', lte: -2 }, text: 'She has a handle of her own now. She thinks you don\'t know it. You taught her everything she\'s using to hide it.' },
        { if: { npc: 'kim', fate: 'thriving' }, text: 'She\'s thriving: honor roll, a scholarship, and a mean streak she mostly aims at deserving targets.' },
        { if: { npc: 'kim', fate: 'follows_in' }, text: 'She followed you in. She\'s good, frighteningly good, and she has none of your excuses.' },
        { if: { npc: 'kim', fate: 'endangered' }, text: 'Someone used her to get to you. She\'s safe, for now. She sleeps with the light on, and she\'s stopped joking about it.' },
        { if: { npc: 'kim', fate: 'estranged' }, text: 'She stopped calling. When you come to dinner, she finds a reason to be at a friend\'s.' },
      ],
    },
    {
      id: 'rosa',
      name: 'Rosa Ferreira',
      faction: 'fac.hood',
      role: "Jax's little sister",
      avatar: 'RF',
      color: '#b8860b',
      social: true,
      startAffinity: 20,
      bio: [
        'Jax\'s little sister: all elbows and questions, always reading three library books at once. She has a heart condition with a long name and a longer bill, and she knows exactly how much it costs, because she reads the envelopes before her mom can hide them.',
        '"Jax says you\'re the smart one. Are you gonna help him, or just let him keep pretending he\'s fine?"',
        { if: { npc: 'rosa', fate: 'treated' }, text: 'Her treatment is paid for. She\'s back at school, running the science fair like a small, merciless general.' },
        { if: { npc: 'rosa', fate: 'worsens' }, text: 'The bills went unpaid. She\'s in and out of Harbor General now, and Jax has started working nights on things he won\'t talk about.' },
        { if: { npc: 'rosa', fate: 'passed' }, text: 'Rosa is gone. The library still has three of her books out. The librarian quietly waived the fines.' },
      ],
    },
  ],
})
