/**
 * PKG-00 — the straight world, the scene and the law (bible §4.3, §4.4).
 * Outer-ring NPCs have no weekly decay (§4.7 decays only the inner circle and the family), except
 * the scene regulars Deadline and byteme, who are on the inner-circle decay list.
 */
import { defineContent } from '@/engine/registry'

export default defineContent({
  npcs: [
    // ── Straight world ───────────────────────────────────────────────────────
    {
      id: 'vale',
      name: 'Marcus Vale',
      faction: 'fac.halcyon',
      role: 'Founder & CEO, Halcyon Systems',
      avatar: 'MV',
      color: '#117a65',
      bio: [
        'Founder and CEO of Halcyon Systems: black turtleneck, white sneakers, a laugh that fills an atrium. He has been on the cover of Port Lumen Business Weekly four times, and in the Lumen Sound Yacht Club bar considerably more.',
        '"I\'m not selling software. I\'m selling the feeling that the future already arrived and you\'re standing in it." It is a very good feeling. People pay a lot for it.',
        { if: { flag: 'a3.truth_t1' }, text: 'You know where his money comes from now. Aperture keeps Halcyon\'s lights on, and Halcyon keeps Aperture\'s shirt clean.' },
        { if: { flag: 'a3.good_soldier' }, text: 'You sabotaged the Meridian job for him. He shook your hand for a long time and said "family" twice.' },
        { if: { npc: 'vale', fate: 'flames_out' }, text: 'Ruined. The scandal took the company, the house and the turtlenecks. Last seen selling timeshares with enormous sincerity.' },
        { if: { npc: 'vale', fate: 'escapes_clean' }, text: 'He cashed out before the fall and now "advises founders" from a boat. The Bureau returns his calls.' },
        { if: { npc: 'vale', fate: 'patron' }, text: 'He keeps your secret and you keep his. His protection covers your friends like an expensive umbrella.' },
        { if: { npc: 'vale', fate: 'exposed' }, text: 'You burned him. He gave one interview, cried beautifully, and has not been seen since.' },
        { if: { npc: 'vale', fate: 'reformed' }, text: 'He cut the dirty money loose. Halcyon got smaller, and he got, somehow, more likeable.' },
      ],
    },
    {
      id: 'dee',
      name: 'Dee Briggs',
      faction: 'fac.halcyon',
      role: 'Your first boss · force of nature',
      avatar: 'DB',
      color: '#c75b12',
      social: true,
      bio: [
        'Dolores "Dee" Briggs runs the CompCastle service bench the way a general runs a war she fully intends to win. The customer is always right, the customer\'s monitor is usually unplugged, and nobody ever needs to tell the customer that.',
        '"We do not tell the customer. We heal the customer. Go heal the customer." She believes RAM is a kind of browser. She is also, somehow, the best manager you will ever have.',
        { if: { flag: 'npc.dee.encouraged' }, text: 'You told her she should run for city council. She laughed so hard she had to sit down. Then she got very quiet and asked what the filing fee was.' },
        { if: { quest: 'fac_halcyon_q1_interview', status: 'completed' }, text: 'The layoff wave swept her off the CompCastle bench. Halcyon hired her as office manager within the month. Their supply closet has never been so feared.' },
        { if: { flag: 'npc.dee.council' }, text: 'Councilwoman Dolores Briggs. She campaigned on potholes, library hours and "computer literacy for every grandmother on the Row." She won by eleven votes and framed the recount.' },
        { if: { npc: 'dee', fate: 'promoted' }, text: 'Through a chain of events nobody can fully explain, Dee is your boss again. She is thrilled. You are adapting.' },
      ],
    },
    {
      id: 'sal',
      name: 'Sal Moretti',
      faction: 'fac.hood',
      role: 'Owner, the Cathode Diner',
      avatar: 'SM',
      color: '#8b4513',
      social: true,
      startAffinity: 20,
      bio: [
        'Sal has run the Cathode, the 24-hour diner under the Sodium Row overpass, since before you were born. Paper hat, forearms like hams, a coffee pot permanently attached to one hand.',
        '"You kids and your modems. In my day we had a rotary phone and a knife. Eat. You look like a dropped call." Every hard conversation in this city happens in one of his booths. He has heard all of them and repeated none.',
        { if: { all: [{ faction: 'fac.hood', gte: 20 }, { var: 'w.cathode_open', eq: 1 }] }, text: 'He saves you the stool at the end of the counter. You never asked. He just started doing it.' },
        { if: { flag: 'side.saved_cathode' }, text: 'The neighbors bought in and saved the Cathode. There\'s a plaque by the register with everyone\'s names on it. Yours is spelled wrong. Sal won\'t fix it.' },
        { if: { var: 'w.cathode_open', eq: 0 }, text: 'The Cathode is closed. Sal still gets up at four and makes coffee for nobody.' },
        { if: { npc: 'sal', fate: 'base' }, text: 'His back room is your base now. He pretends not to know what goes on back there and charges you for the pie.' },
        { if: { npc: 'sal', fate: 'took_a_fall' }, text: 'Sal took a fall to keep the Row out of it. He\'d do it again. He said so, to the judge, twice.' },
      ],
    },
    {
      id: 'grace',
      name: 'Grace Okafor',
      handle: 'gracenote',
      role: 'ER nurse, Harbor Point General',
      avatar: 'GO',
      color: '#2e8b57',
      social: true,
      romanceable: true,
      startAffinity: 10,
      decay: 1,
      baseline: 25,
      bio: [
        'An ER nurse at Harbor Point General: night shifts, steady hands, and a laugh that arrives half a second before she decides whether you\'ve earned it. She has seen every kind of wound there is and has opinions on all of them.',
        '"You keep two lives. I\'m a nurse. I\'m very good at knowing when someone\'s hiding a wound. I\'m asking which one you\'re bringing to dinner."',
        { if: { quest: 'main_a2_q4_moms_illness' }, text: 'She was on shift the night Mom came in. She remembered your name the next morning, which almost nobody at a hospital does.' },
        { if: { npc: 'grace', romance: 'flirting' }, text: 'You\'ve started timing your coffee runs to the end of her shift. She has noticed. She\'s letting you.' },
        { if: { npc: 'grace', romance: 'dating' }, text: 'You\'re seeing each other. Dinners get interrupted by pagers, hers and yours. She wins that contest every time.' },
        { if: { npc: 'grace', romance: 'partner' }, text: 'You live together. Her scrubs, your cables, one shared and heavily negotiated closet.' },
        { if: { npc: 'grace', romance: 'engaged' }, text: 'Engaged. She said yes and then asked, very calmly, if there was anything else you needed to tell her first.' },
        { if: { npc: 'grace', romance: 'married' }, text: 'Married. She still checks your pupils when you come home late. You still let her.' },
        { if: { npc: 'grace', romance: 'ex' }, text: 'It ended. You still drive past Harbor General on the way to places that aren\'t on the way.' },
        { if: { npc: 'grace', fate: 'whistleblower' }, text: 'She saved the ward and went public about the records. The hospital board hates her. Her patients send cards.' },
        { if: { npc: 'grace', fate: 'collateral' }, text: 'Your world reached her. She\'s safe now, mostly. She changed the locks and didn\'t tell you the new combination.' },
        { if: { npc: 'grace', fate: 'left' }, text: 'She found out, or you chose the other life. Either way, she left. She was right to.' },
      ],
    },
    {
      id: 'okoro',
      name: 'Prof. Ada Okoro',
      faction: 'fac.halcyon',
      role: 'Professor of Computer Science, Lumen State',
      avatar: 'AO',
      color: '#4b5d8a',
      social: true,
      startAffinity: 5,
      bio: [
        'Professor Ada Okoro runs the systems lab in the CS basement at Lumen State: tweed, chalk dust, and a whiteboard that has not been fully erased since 1994. Her lectures start late and end with applause.',
        '"Grants are like weather. You don\'t ask the cloud where the rain came from." A pause. "Though lately I\'ve started asking."',
        { if: { any: [{ enrolled: true }, { degree: true }] }, text: 'Office hours with her are a cup of tea, a stack of your code printed out, and red ink in quantities that feel personal.' },
        { if: { npc: 'okoro', fate: 'mentor' }, text: 'She wrote you a reference so good it is slightly embarrassing to read.' },
        { if: { npc: 'okoro', fate: 'complicit' }, text: 'She chose not to look at where her grant money came from. She looks tired these days, in a way tenure doesn\'t fix.' },
        { if: { npc: 'okoro', fate: 'ally' }, text: 'She helped you document the grant. She says she\'s too old to be frightened of anything except bad footnotes.' },
      ],
    },
    {
      id: 'northlink_wes',
      name: 'Wes Tran',
      handle: 'noc_wes',
      faction: 'fac.halcyon',
      role: 'Operations manager, NorthLink ISP',
      avatar: 'WT',
      color: '#3d6b9e',
      social: true,
      startAffinity: 5,
      bio: [
        'Wes Tran runs operations at NorthLink, the city\'s dial-up-and-someday-broadband provider, from a windowless room full of blinking lights and one heroically overworked space heater. He wears a headset even when he isn\'t on a call.',
        '"We keep the logs because the law says to. Soon the law\'s gonna say keep more. I just run the pipe, man." He says it like a joke. It gets less funny every year.',
        { if: { npc: 'northlink_wes', fate: 'whistle' }, text: 'You and Wes leaked the tap together. He got fired, then interviewed by three reporters, then quietly rehired when the story broke.' },
        { if: { npc: 'northlink_wes', fate: 'company_man' }, text: 'He installed the tap and got the promotion. He has a window now. He keeps the blinds closed.' },
      ],
    },

    // ── The law ──────────────────────────────────────────────────────────────
    {
      id: 'reyes',
      name: 'Agent Dana Reyes',
      faction: 'fac.bureau',
      role: 'Field agent, the Bureau',
      avatar: 'DR',
      color: '#34495e',
      bio: [
        'Special Agent Dana Reyes: sensible shoes, a notebook she actually writes in, and the particular calm of someone who has sat across a table from a great many liars.',
        '"I came here to catch the people hollowing out this city. Turns out my own office is renting their tools." A true believer, learning slowly and painfully what her badge is attached to.',
        { if: { flag: 'fac.bureau.informant' }, text: 'You\'re her asset. She calls every Tuesday. She always asks whether you\'ve eaten, which is either tradecraft or kindness, and she won\'t tell you which.' },
        { if: { npc: 'reyes', fate: 'handler' }, text: 'Your handler and, against all odds, your protector. When the office wanted to throw you away, she lost the paperwork.' },
        { if: { npc: 'reyes', fate: 'broken' }, text: 'She blew the whistle on her own agency. They took her badge. She kept the notebook.' },
        { if: { npc: 'reyes', fate: 'nemesis' }, text: 'She hunts you now. It isn\'t personal. That\'s what makes it so bad.' },
        { if: { npc: 'reyes', fate: 'turned' }, text: 'She quit. Now she consults on reform, and she\'s the only person in any room who has read everything.' },
      ],
    },
    {
      id: 'marlow',
      name: 'SAC Duke Marlow',
      faction: 'fac.bureau',
      role: 'Special Agent in Charge, Port Lumen office',
      avatar: 'DM',
      color: '#1c2833',
      bio: [
        'Special Agent in Charge Duke Marlow runs the Bureau\'s Port Lumen office from a corner room with a flag, a putter, and a view of the Meridian Trust tower he admires a little too openly.',
        '"Aperture hands us a map of every bad actor in this city. You don\'t set fire to the map." He means it. He also means to be promoted.',
        { if: { npc: 'marlow', fate: 'exposed' }, text: 'Exposed. The hearings ran for weeks. He kept the putter.' },
        { if: { npc: 'marlow', fate: 'promoted' }, text: 'Promoted to headquarters. The map went with him.' },
      ],
    },
    {
      id: 'calderon',
      name: 'Det. Ruth Calderon',
      role: 'Detective, PD Cyber Unit ("the Cage")',
      avatar: 'RC',
      color: '#7b5e2e',
      bio: [
        'Detective Ruth Calderon runs the Port Lumen PD Cyber Unit: three detectives, one closet of confiscated hardware and a modem from 1997, all behind the chain-link corner of the evidence floor that everyone calls the Cage.',
        '"I\'ve got a budget of nothing and a modem from 1997, and I\'m still going to ruin somebody\'s year." She is local, she is stubborn, and she is not the Bureau. She would like that on the record.',
        { if: { flag: 'npc.calderon.ally_case' }, text: 'You fed her a real case. She closed it the old-fashioned way and bought you the worst coffee in the precinct to say thanks.' },
        { if: { npc: 'calderon', fate: 'expanded' }, text: 'Federal money came, and the Cage became a real unit with real toys and real reach. She isn\'t sure she likes what it\'s becoming.' },
        { if: { npc: 'calderon', fate: 'forced_out' }, text: 'They squeezed her budget until there was nothing left. She keeps the Cage\'s old nameplate in her glovebox.' },
        { if: { npc: 'calderon', fate: 'the_one_who_cuffs_you' }, text: 'She was the one who put the cuffs on. She did it gently, and she read you your rights like she meant every word.' },
      ],
    },

    // ── Aperture ─────────────────────────────────────────────────────────────
    {
      id: 'kroll',
      name: 'Vanessa Kroll',
      faction: 'fac.aperture',
      role: 'VP of Special Accounts, Aperture',
      avatar: 'VK',
      color: '#7b1f3f',
      bio: [
        'Vanessa Kroll, Vice President of Special Accounts at Aperture Data Solutions. Silver bob, reading glasses on a chain, and a laugh that makes you feel like the smartest person at the table. She remembers your drink order, your mother\'s name and your birthday.',
        '"I\'m not the bad guy. I\'m the market. Aren\'t you glad it\'s someone who takes you to dinner first?" She has never told you a lie. That is the frightening part.',
        { if: { flag: 'npc.kroll.wary' }, text: 'She is careful around you now. She smiles just as warmly and checks her pockets after you leave.' },
        { if: { flag: 'npc.kroll.wants_you' }, text: 'She has been grooming you for something. PARALLAX thinks you would be good at her job. So does she.' },
        { if: { npc: 'kroll', fate: 'boss' }, text: 'You work for her. She\'s a wonderful boss. That\'s the problem.' },
        { if: { npc: 'kroll', fate: 'cut_loose' }, text: 'Her superiors burned her. She\'s on her own now, in a very nice apartment, waiting to see what you\'ll do.' },
        { if: { npc: 'kroll', fate: 'flips' }, text: 'She turned on the conspiracy, gracefully, with a lawyer on each side and a smile for the cameras.' },
        { if: { npc: 'kroll', fate: 'arrested' }, text: 'Arrested. She walked out of Aperture in handcuffs and still said good morning to the receptionist by name.' },
        { if: { npc: 'kroll', fate: 'made_you' }, text: 'She gave you her seat. She\'s retired somewhere with a sea view. Her birthday card arrives on time every year.' },
      ],
    },
    {
      id: 'hollis',
      name: 'Miles Hollis',
      faction: 'fac.aperture',
      role: '"Compliance," Aperture',
      avatar: 'MH',
      color: '#555b66',
      startAffinity: -10,
      bio: [
        'Miles Hollis handles "Compliance" at Aperture: grey suit, grey tie, grey everything, and a leather folio he never opens in front of you. He speaks in complete sentences and closes each one like a door.',
        '"Vanessa collects strays. I close files. You are, at present, an open file." He wants Kroll\'s chair and regards you as a liability with a pulse.',
        { if: { npc: 'hollis', fate: 'rising' }, text: 'He took the seat when Kroll fell. The first thing he did was open your file.' },
        { if: { npc: 'hollis', fate: 'neutralized' }, text: 'You gave Kroll what she needed to bury him. He\'s in a regional office now, closing smaller files.' },
        { if: { npc: 'hollis', fate: 'your_ally' }, text: 'You backed him over Kroll. He is grateful in the way a lock is grateful for its key.' },
      ],
    },

    // ── The scene ────────────────────────────────────────────────────────────
    {
      id: 'deadline',
      name: 'Deadline',
      handle: 'Deadline',
      faction: 'fac.loft',
      role: 'Scene elder · cautionary tale',
      avatar: 'DL',
      color: '#6e5a3a',
      social: true,
      startAffinity: 10,
      decay: 1,
      baseline: 20,
      bio: [
        'Theo Marsh, known to three generations of the scene as Deadline. Fifties, a beard like a burst sofa, usually a little drunk and always a little ominous. He sits in the back room\'s worst chair because it\'s the one nearest the door.',
        '"\'94. Confiscated my rig, my books, my dog\'s vet records. Did fourteen months. Learn from me: back up your life, not your data." He means it as a joke. Nobody laughs, including him.',
        'He has an old dog he loves more than most people, and a phone number for a lawyer written on the inside of his wrist, just in case.',
        { if: { npc: 'deadline', fate: 'mentor' }, text: 'He\'s been teaching you not to make his mistakes, which mostly means making you back things up in triplicate.' },
        { if: { npc: 'deadline', fate: 'relapse' }, text: 'You pulled him into one last job. He was brilliant. He hasn\'t stopped shaking since.' },
        { if: { npc: 'deadline', fate: 'saves_you' }, text: 'When the walls closed in, he knew a way out nobody had used since \'94. He walked you through it without once saying "I told you so."' },
        { if: { npc: 'deadline', fate: 'passed' }, text: 'Deadline is gone. The worst chair in the back room stays empty. Nobody sits in it. Nobody has to say why.' },
      ],
    },
    {
      id: 'byteme',
      name: 'byteme',
      handle: 'byteme',
      faction: 'fac.loft',
      role: 'Script kiddie · Loft mascot',
      avatar: 'b',
      color: '#27ae60',
      social: true,
      startAffinity: 20,
      decay: 1,
      baseline: 25,
      bio: [
        'Kevin Pham, sixteen, types exclusively in lowercase and exclusively at full speed. On the board he\'s byteme, and he thinks you are the coolest person alive, which is a lot of pressure.',
        'He grabs every program the forum swears is "undetectable" and runs it before reading a word, then pages you in a panic. "its fine right. right??" It is not fine. He is a kid, and he is brilliant, and he is going to get caught unless somebody teaches him how to be careful.',
        { if: { flag: 'npc.byteme.used' }, text: 'You taught him things he wasn\'t ready to know, and then you needed him. He never said no to you. He never says no to you.' },
        { if: { npc: 'byteme', fate: 'pro' }, text: 'He grew careful. He even uses capital letters now, sometimes, when it matters. One day he\'s going to be better than you.' },
        { if: { npc: 'byteme', fate: 'arrested_young' }, text: 'Arrested before he was old enough to vote. His mother won\'t look at you in the street.' },
        { if: { npc: 'byteme', fate: 'turns' }, text: 'He felt used, and he turned. There\'s a Bureau file with your name in it, written in all lowercase.' },
        { if: { npc: 'byteme', fate: 'dead' }, text: 'Kevin is dead. He was younger than you were when you started. You still have his last page saved.' },
      ],
    },
    {
      id: 'switch',
      name: 'Switch',
      handle: 'Switch',
      faction: 'fac.loft',
      role: 'Loft pragmatist · runs the trades',
      avatar: 'SW',
      color: '#9a7d0a',
      social: true,
      startAffinity: 5,
      bio: [
        'Ray Delgado, Switch to everyone: a leather jacket in August and a calculator watch he insists is ironic. He runs half the Loft\'s trades out of a duffel bag and knows exactly what every one of them is worth.',
        '"Corvid wants a commons. Commons don\'t pay rent. I\'m getting the scene paid before Aperture takes it for free." He isn\'t wrong. That is what makes him dangerous.',
        { if: { flag: 'npc.switch.courted' }, text: 'You took his side in the back room once. He hasn\'t let you forget it, in the friendliest possible way.' },
        { if: { npc: 'switch', fate: 'sellout' }, text: 'He led the Loft into Aperture\'s arms. The scene got paid. It stopped being a scene.' },
        { if: { npc: 'switch', fate: 'converted' }, text: 'You talked him back to the commons. He still counts everything, but now he counts it out loud, for everyone.' },
        { if: { npc: 'switch', fate: 'casualty' }, text: 'Aperture used him and threw him away. He sells used pagers at the swap meet now and won\'t talk about it.' },
        { if: { npc: 'switch', fate: 'new_sysop' }, text: 'He took the board when Corvid fell. He runs it like a business. It\'s the best-run business on the Row.' },
      ],
    },
    {
      id: 'dialtone',
      name: 'Marge Osgood',
      handle: 'dialtone',
      faction: 'fac.hood',
      role: 'Retired exchange operator · phone-line legend',
      avatar: '☎',
      color: '#7d3c98',
      social: true,
      startAffinity: 10,
      bio: [
        'Margaret "Marge" Osgood patched this city\'s telephone calls for thirty years at the old Cannery-Millgate exchange. Seventies, cardigan, cat-eye glasses, and a memory for wiring diagrams that would embarrass a computer.',
        'On the old phone-phreak boards they called her dialtone, and some of the grognards still lower their voices when they say it. "Ask me nicely, love, and I\'ll tell you which wires they forgot to disconnect."',
        { if: { flag: 'side.met_dialtone' }, text: 'You met her teaching seniors to use email in the church basement. She corrected your wiring in front of everyone. You deserved it.' },
        { if: { all: [{ item: 'exchange_keys' }, { npc: 'dialtone', fateNot: 'passed_keys' }] }, text: 'Her keys are in your pocket, every one tagged in faded ballpoint. She made you promise to bring them back, "and the building with them, if you can manage it."' },
        { if: { npc: 'dialtone', fate: 'honored' }, text: 'The scene\'s elder, alive and bossy. She still walks the Row every morning, counting the old telephone poles like rosary beads.' },
        { if: { npc: 'dialtone', fate: 'evicted' }, text: 'The Millgate redevelopment took her flat. She lives with her niece in Ridgeport now and phones you collect, on principle.' },
        { if: { npc: 'dialtone', fate: 'passed_keys' }, text: 'Marge is gone. She left you her keys and a note in careful operator\'s handwriting: "Mind the frame room. It floods."' },
      ],
    },
  ],
})
