import { defineContent } from '@/engine/registry'

/**
 * ECON — Books. Each is a study multiplier for one skill (or, for the catalog, all skills).
 * Titles are invented parodies of the era's technical shelf. Priced $15–80; owning the book
 * boosts XP while you study that skill.
 */
export default defineContent({
  items: [
    {
      id: 'book_programming',
      name: 'Teach Yourself Programming in 21 Weeks',
      category: 'book',
      shop: 'books',
      price: 30,
      desc: 'A doorstop of a book that is honest about the timeline in a way the 21-*days* competitor never was. The margins fill up with your own swearing.',
      mods: [{ key: 'xp.programming', mult: 1.2 }],
    },
    {
      id: 'book_programming_adv',
      name: 'The Pragmatic Compiler',
      category: 'book',
      shop: 'books',
      price: 65,
      desc: 'The advanced text everyone quotes and nobody finishes. You are going to finish it, out of spite, and it will change how you think.',
      mods: [{ key: 'xp.programming', mult: 1.35 }],
    },
    {
      id: 'book_networking',
      name: 'Packets & Pipes',
      category: 'book',
      shop: 'books',
      price: 40,
      desc: 'Explains how a message actually crosses a city, one hop at a time, with diagrams a tired person can follow at 3 a.m.',
      mods: [{ key: 'xp.networking', mult: 1.25 }],
    },
    {
      id: 'book_intrusion',
      name: 'Doors, Windows & Locks',
      category: 'book',
      shop: 'books',
      price: 45,
      desc: 'A survey of how systems fail written by someone clearly on the wrong side of a plea deal. Reads like a heist novel with footnotes.',
      mods: [{ key: 'xp.intrusion', mult: 1.25 }],
    },
    {
      id: 'book_crypto',
      name: 'Applied Ciphers',
      category: 'book',
      shop: 'books',
      price: 55,
      desc: 'Where the math finally clicks. Also where you learn most locks are strong and most doors are left open anyway.',
      mods: [{ key: 'xp.cryptography', mult: 1.3 }],
    },
    {
      id: 'book_hardware',
      name: 'The Beige Bible',
      category: 'book',
      shop: 'books',
      price: 35,
      desc: 'Every jumper, every IRQ conflict, every ritual for coaxing a dead board back to life. Comes with a free static wrist strap that never works.',
      mods: [{ key: 'xp.hardware', mult: 1.25 }],
    },
    {
      id: 'book_systems',
      name: 'UNIX for the Sleepless',
      category: 'book',
      shop: 'books',
      price: 40,
      desc: 'A friendly walk through the command line for people who talk to their computers at night. Fewer than half the jokes land, but the ones that do are perfect.',
      mods: [{ key: 'xp.systems', mult: 1.25 }],
    },
    {
      id: 'book_social',
      name: 'How to Win Sysops & Influence Ops',
      category: 'book',
      shop: 'books',
      price: 25,
      desc: 'A self-help paperback repurposed, cover to cover, for talking your way past a suspicious voice on a phone. Weirdly effective. Slightly sinister.',
      mods: [{ key: 'xp.social', mult: 1.2 }],
    },
    {
      id: 'book_opsec',
      name: 'Cover Your Tracks',
      category: 'book',
      shop: 'books',
      price: 50,
      desc: 'Written by a man who did fourteen months and clearly thought about nothing else the whole time. Chapter one: back up your life, not your data.',
      mods: [{ key: 'xp.opsec', mult: 1.3 }],
    },
    {
      id: 'book_business',
      name: 'The Lean Garage',
      category: 'book',
      shop: 'books',
      price: 28,
      desc: 'How to turn a hobby into a paying gig without becoming the kind of person who says "synergy" out loud. Optimistic to a fault.',
      mods: [{ key: 'xp.business', mult: 1.2 }],
    },
    {
      id: 'book_fitness',
      name: "The Desk Jockey's Comeback",
      category: 'book',
      shop: 'books',
      price: 18,
      desc: 'A gentle, guilt-free program for people whose main exercise is carrying a CRT. Starts with "stand up." You will find this harder than expected.',
      mods: [{ key: 'xp.fitness', mult: 1.2 }],
    },
    {
      id: 'book_catalog',
      name: 'The Whole Earth Hacker Catalog',
      category: 'book',
      shop: 'books',
      price: 80,
      desc: 'A fat, chaotic, lovingly indexed compendium of everything the scene knows and half of what it only thinks it knows. Broadens you a little in every direction.',
      mods: [{ key: 'xp.all', mult: 1.12 }],
    },
  ],
})
