import { dayOf } from '@/engine/calendar'
import { defineContent } from '@/engine/registry'

/**
 * ECON — Additional procedural FREELANCE templates, added in the v2 pass so the bigger gig board
 * (8 offers per turn) stays fresh. Legit work: no heat, no cred; it pays, trains skills, and — for
 * the neighborhood jobs — earns a little goodwill with the Row. Tiers gate on programming/business
 * (engine `FREELANCE_TIERS`); some also gate on era (`day`), world state (`w.broadband`), faction
 * rep, or the career track the player currently works.
 *
 * Pay ranges here are FINAL (the engine's freelance multiplier is retired = 1), sized to the same
 * per-tier bands as the base freelance package (weekly turns: short gigs, 2–4 per turn off a full queue):
 *   t1 ~4–12 h $20–60 · t2 ~6–13 h $60–145 · t3 ~9–16 h $140–320 · t4 ~10–18 h $235–780 ·
 *   t5 ~11–18 h $780–1,460
 */

const Y2008 = dayOf(2008, 0, 1)

export default defineContent({
  contractTemplates: [
    // ─────────────────────────── TIER 1 ────────────────────────────
    {
      id: 'f1_auction_lister',
      kind: 'freelance',
      tier: 1,
      titles: ['Sell {target} online', "List {target}'s attic", 'Auction wrangler for {target}'],
      descs: [
        '{target} has a garage of "collectibles" and no idea how the auction site works. Photograph it, write the listings, field the questions from people who collect exactly this and are furious about it. Honest, tedious money.',
        'Turn {target}\'s clutter into cash. Take the pictures, write the breathless descriptions ("RARE!! VINTAGE!!"), and handle the shipping math. They pay you a cut and a sandwich.',
        '{target} inherited a house full of stuff and wants it gone by spring. Run the online auctions, keep the feedback clean, and be gentle about the ones that are actually worthless.',
      ],
      targets: ['a downsizing retiree', 'an estate sale', 'a hoarder with taste', 'a widow clearing a workshop'],
      clients: ['a friend of the family', 'a neighbor', 'an overwhelmed executor', 'a Row regular'],
      skills: ['business'],
      dc: [8, 11],
      hours: [6, 12],
      pay: [20, 60],
      heat: [0, 0],
      cred: [0, 0],
      rep: { 'fac.hood': 1 },
    },
    {
      id: 'f1_photo_scan',
      kind: 'freelance',
      tier: 1,
      titles: ['Digitize {target}\'s photos', 'Scan the albums for {target}', 'Save {target}\'s memories'],
      descs: [
        '{target} has forty years of photos curling in shoeboxes and a fear the colors are fading (they are). Scan them, clean them up, burn them to a CD, and hand back a small resurrection.',
        'Scan {target}\'s family slides before the projector eats another one. Fiddly, patient work, and every third image makes the client cry, which extends the job considerably.',
        '{target} wants the wedding photos on the computer "so the kids can have them." Digitize the lot, label them right, and be prepared to hear the story behind each one. Twice.',
      ],
      targets: ['a grandparent', 'a genealogy buff', 'a retired couple', 'a family historian'],
      clients: ['a sentimental client', 'a grateful family', 'a church group', 'a neighbor with a shoebox'],
      skills: ['hardware'],
      dc: [8, 10],
      hours: [4, 10],
      pay: [20, 55],
      heat: [0, 0],
      cred: [0, 0],
      rep: { 'fac.hood': 1 },
    },
    {
      id: 'f1_homepage_fix',
      kind: 'freelance',
      tier: 1,
      titles: ["Fix {target}'s homepage", 'Rescue the free site for {target}', 'Un-break {target}'],
      descs: [
        '{target} built their own free-host homepage and now half the images are red X\'s and the counter is stuck at 000042. Fix the broken links, unstick the counter, and quietly delete the auto-playing MIDI. (Leave one, for the soul.)',
        '{target}\'s personal site "broke itself" — meaning they edited it in a word processor again. Clean up the markup, restore the guestbook, and gently take away their editing privileges.',
        'The fan page {target} runs was working "yesterday." It was not. Sort out the tangled frames, fix the marquee, and get the animated flames flying the right direction again.',
      ],
      targets: ['a hobbyist', 'a fan-club president', 'a very online uncle', 'a poetry blogger before that was a word'],
      clients: ['an enthusiastic amateur', 'a forum acquaintance', 'a webring neighbor', 'a friend of a friend'],
      skills: ['programming'],
      dc: [8, 10],
      hours: [4, 9],
      pay: [20, 50],
      heat: [0, 0],
      cred: [0, 0],
    },
    {
      id: 'f1_printer_whisper',
      kind: 'freelance',
      tier: 1,
      titles: ["Make {target}'s printer behave", 'Exorcise the printer at {target}', 'Printer house call: {target}'],
      descs: [
        'The printer at {target} prints everything sideways, in cyan, on the wrong tray, then jams out of spite. Reinstall the driver, feed it the right cable, and perform whatever small ritual it demands. Cash and a legend are your reward.',
        '{target}\'s printer works for everyone except {target}. Diagnose the haunting, fix the queue, and explain — for the fourth time — what "offline" means. They will not retain it. You will be back.',
        'The office at {target} shares one printer and a great deal of resentment. Untangle the network queue, label the trays, and broker a fragile peace between the accounting department and the color cartridge.',
      ],
      targets: ['a home office', 'a two-person shop', 'a very frustrated dad', 'a church office'],
      clients: ['a defeated small-business owner', 'a neighbor at wit\'s end', 'a referral', 'a repeat customer (always the printer)'],
      skills: ['hardware', 'systems'],
      dc: [8, 11],
      hours: [4, 9],
      pay: [20, 55],
      heat: [0, 0],
      cred: [0, 0],
      rep: { 'fac.hood': 1 },
    },
    {
      id: 'f1_cd_burn',
      kind: 'freelance',
      tier: 1,
      titles: ['Burn {target} to CD', 'Transfer the tapes for {target}', 'Digitize {target}\'s videos'],
      descs: [
        '{target} wants the home movies off the camcorder tapes before the tapes turn to dust. Rig the capture, sit through every birthday and recital in real time, and burn the results to discs that will outlive the format by a decade.',
        'Transfer {target}\'s wedding video to CD so they can "email it to Aunt Carol" (you will explain file sizes gently). Slow, real-time work; bring a book and infinite patience.',
        '{target} has a stack of tapes labeled only in mood ("good one," "the sad Christmas," "DO NOT ERASE"). Capture them all, burn them, and preserve the labels exactly, because the labels are the real archive.',
      ],
      targets: ['a young family', 'a couple\'s anniversary', 'a retiree', 'a proud new grandparent'],
      clients: ['a nostalgic parent', 'a family friend', 'a neighbor', 'a grateful client'],
      skills: ['hardware'],
      dc: [8, 10],
      hours: [6, 12],
      pay: [20, 60],
      heat: [0, 0],
      cred: [0, 0],
    },
    {
      id: 'f1_dialup_tune',
      kind: 'freelance',
      tier: 1,
      titles: ["Speed up {target}'s connection", 'Tune the modem for {target}', 'Fix the busy signal at {target}'],
      descs: [
        '{target} swears the internet is "slower than the neighbors\'." Tune the modem init string, chase the line noise, move the phone off the same jack, and squeeze another few hundred baud out of tired copper. They will be thrilled by numbers they don\'t understand.',
        '{target} keeps getting knocked offline whenever someone picks up the phone. Sort the wiring, add a filter, teach the household the sacred rule, and restore a fragile digital peace.',
        'The connection at {target} drops at exactly 8 p.m. every night (it is the cordless phone). Diagnose the interference, relocate the base station, and become a household name for a week.',
      ],
      targets: ['a dial-up household', 'a rural client', 'a big family on one line', 'a night-owl student'],
      clients: ['a frustrated subscriber', 'a neighbor', 'a word-of-mouth referral', 'a patient retiree'],
      skills: ['networking'],
      dc: [9, 11],
      hours: [4, 9],
      pay: [20, 50],
      heat: [0, 0],
      cred: [0, 0],
    },

    // ─────────────────────────── TIER 2 ────────────────────────────
    {
      id: 'f2_forum_install',
      kind: 'freelance',
      tier: 2,
      titles: ['Stand up a message board for {target}', 'Build a community for {target}', 'Give {target} a forum'],
      descs: [
        '{target} wants "one of those message board things" so their customers can talk to each other (a decision they will regret and you will not warn them about). Install it, theme it, set up the moderators, and hand over the keys to a small kingdom of flame wars.',
        'Set up a proper discussion board for {target}: categories, avatars, signatures, the works. The install is easy; the hard part is explaining that you cannot make people be nice on the internet.',
        '{target} runs a hobby club and wants it online. Build the forum, wire up the registration, add the "who\'s online" widget they specifically requested, and watch a community bloom out of nothing.',
      ],
      targets: ['a hobby club', 'a small brand', 'a local sports league', 'a neighborhood association'],
      clients: ['a club president', 'an enthusiastic owner', 'a volunteer webmaster', 'a community organizer'],
      skills: ['programming'],
      dc: [12, 15],
      hours: [6, 12],
      pay: [60, 135],
      heat: [0, 0],
      cred: [0, 0],
    },
    {
      id: 'f2_backup_system',
      kind: 'freelance',
      tier: 2,
      titles: ['Set up backups for {target}', 'Protect the data at {target}', 'Give {target} a safety net'],
      descs: [
        '{target} has never once backed up the machine their entire business lives on, and they finally had a scare. Set up a real backup routine, test the restore (the part everyone skips), and give them the gift of sleeping at night.',
        'Design a backup system for {target} that actually runs without a human remembering to run it. Rotate the tapes, verify the restores, document the whole thing for when you\'re not there. Unglamorous heroism.',
        '{target} lost a week of work to a dead drive and never wants to feel that again. Build them redundant, automatic, tested backups, and explain — kindly — that "I email it to myself" is not a strategy.',
      ],
      targets: ['a design studio', 'an accounting practice', 'a small manufacturer', 'a photographer'],
      clients: ['a spooked owner', 'an office manager', 'a sole proprietor', 'a practice administrator'],
      skills: ['systems'],
      dc: [12, 15],
      hours: [6, 12],
      pay: [65, 140],
      heat: [0, 0],
      cred: [0, 0],
    },
    {
      id: 'f2_crm',
      kind: 'freelance',
      tier: 2,
      titles: ['Build a contact system for {target}', 'Organize the clients of {target}', 'Give {target} a database'],
      descs: [
        '{target} tracks their entire customer base on index cards, in a shoebox, in an order known only to God. Build them a real contact database, import the cards, and add the follow-up reminders that will double their repeat business.',
        'Design a simple system for {target} to remember who their customers are, what they bought, and when to call them again. Not glamorous, wildly valuable, and the client will treat you like a wizard.',
        '{target} keeps losing sales because they forget to follow up. Build a contact-and-reminder tool that fits how they actually work, migrate the shoebox, and watch their numbers climb.',
      ],
      targets: ['a real-estate agent', 'a small agency', 'a wedding planner', 'a home contractor'],
      clients: ['a hustling solo pro', 'a small partnership', 'an ambitious owner', 'a referral-driven business'],
      skills: ['programming', 'business'],
      dc: [12, 15],
      hours: [7, 13],
      pay: [70, 145],
      heat: [0, 0],
      cred: [0, 0],
    },
    {
      id: 'f2_wifi_office',
      kind: 'freelance',
      tier: 2,
      titles: ['Bring wireless to {target}', 'Cut the cables at {target}', 'Set up Wi-Fi for {target}'],
      descs: [
        '{target} heard you can have the internet "without wires now" and wants in. Set up the access point, lock it down so the coffee shop next door isn\'t freeloading, and walk them through the magic of a laptop on the couch.',
        'Add wireless to {target}\'s office so the meeting room stops being a cable graveyard. Survey for dead spots, place the access points, and teach everyone the password (which they will immediately tape to a monitor).',
        '{target} wants laptops to work anywhere in the building. Design the wireless coverage, secure it properly, and gently explain why the microwave kills the signal in the break room.',
      ],
      targets: ['a small office', 'a cafe', 'a real-estate branch', 'a design firm'],
      clients: ['a trend-chasing owner', 'an office manager', 'a hip small business', 'a partner who saw an ad'],
      skills: ['networking'],
      dc: [12, 15],
      hours: [6, 12],
      pay: [70, 145],
      heat: [0, 0],
      cred: [0, 0],
      available: { var: 'w.broadband', gte: 1 },
    },
    {
      id: 'f2_inventory_scanner',
      kind: 'freelance',
      tier: 2,
      titles: ['Barcode the stockroom at {target}', 'Inventory system for {target}', 'Count everything at {target}'],
      descs: [
        '{target} does inventory by walking the aisles with a clipboard and a growing sense of despair. Set up barcode scanning tied to their records, tag the shelves, and turn a two-day nightmare into a two-hour afternoon.',
        'Wire {target} a scanner-based stock system so they finally know what they have without counting it by hand. Fiddly hardware, satisfying result, and a client who weeps with relief at their first accurate count.',
        '{target} is bleeding money to shrinkage and guesswork. Build them barcode inventory, train the staff, and hand over a stockroom that adds up for the first time in the shop\'s history.',
      ],
      targets: ['a hardware store', 'a warehouse', 'a pharmacy', 'a parts distributor'],
      clients: ['a hands-on owner', 'a warehouse manager', 'a franchise operator', 'a small-chain buyer'],
      skills: ['hardware', 'systems'],
      dc: [13, 15],
      hours: [7, 13],
      pay: [70, 145],
      heat: [0, 0],
      cred: [0, 0],
    },
    {
      id: 'f2_church_site',
      kind: 'freelance',
      tier: 2,
      titles: ['Rebuild the website for {target}', 'Bring {target} online properly', 'Give {target} a real site'],
      descs: [
        '{target} — the Row\'s beating heart — has a website from 1998 that lists a fax number and a pastor who retired. Rebuild it: the schedule, the newsletter, the photo gallery of the potluck. Small pay, big goodwill.',
        '{target} runs the neighborhood and needs a site that actually helps people: hours, contacts, the volunteer sign-up, the food-bank list. Build it clean, build it kind, and the whole Row hears your name at dinner.',
        'The community group at {target} wants a website that welcomes people instead of confusing them. Design something warm and simple, teach a volunteer to update it, and become quietly beloved.',
      ],
      targets: ['the Cannery Row community center', 'a Row church', 'the neighborhood food bank', 'a volunteer association'],
      clients: ['a tireless volunteer', 'a Row organizer', 'a church secretary', 'a community elder'],
      skills: ['programming'],
      dc: [11, 14],
      hours: [6, 11],
      pay: [60, 135],
      heat: [0, 0],
      cred: [0, 0],
      rep: { 'fac.hood': 2 },
      weight: 2,
    },

    // ─────────────────────────── TIER 3 ────────────────────────────
    {
      id: 'f3_cms',
      kind: 'freelance',
      tier: 3,
      titles: ['Build a content system for {target}', 'Give {target} a real publishing platform', 'Power the site for {target}'],
      descs: [
        '{target} publishes daily and edits the site by hand-coding every page, which is exactly as sustainable as it sounds. Build them a proper content system so the writers can write and the site can grow. Serious work, serious spec, a real check.',
        'Design and build a publishing platform for {target}: articles, categories, an archive, a comment system they\'ll turn off within a month. Months of work and a client who\'ll refer you across the whole industry.',
        '{target} is drowning in its own success — too much content, too few hands, a site held together by one exhausted webmaster. Build the system that scales them, and become indispensable.',
      ],
      targets: ['an online magazine', 'a regional news site', 'a busy blog network', 'a review site'],
      clients: ['an editor-in-chief', 'a digital director', 'a burned-out webmaster', 'a media founder'],
      skills: ['programming'],
      dc: [15, 18],
      hours: [9, 16],
      pay: [140, 300],
      heat: [0, 0],
      cred: [0, 0],
      available: { var: 'w.broadband', gte: 1 },
    },
    {
      id: 'f3_data_recovery',
      kind: 'freelance',
      tier: 3,
      titles: ['Recover the data at {target}', 'Bring {target}\'s server back', 'Salvage {target}'],
      descs: [
        '{target}\'s main server died with no working backup and their whole business inside it. This is a rescue: coax the failing drives, reconstruct what you can, and be honest about what\'s gone. High stakes, high gratitude, high rate.',
        'A disaster call from {target}: the RAID lied about being fine for years and now it isn\'t. Recover the databases, rebuild the system properly this time, and hold their hand through the parts that can\'t be saved.',
        '{target} had a fire, a flood, or a very bad Tuesday, and their systems are wreckage. Salvage the data, stand up a clean replacement, and be the calm professional in someone\'s worst week.',
      ],
      targets: ['a law firm', 'a medical practice', 'a manufacturer', 'an accounting office'],
      clients: ['a panicking managing partner', 'a practice owner in crisis', 'an operations lead', 'a CFO watching the clock'],
      skills: ['systems', 'hardware'],
      dc: [16, 19],
      hours: [9, 15],
      pay: [160, 320],
      heat: [0, 0],
      cred: [0, 0],
    },
    {
      id: 'f3_api_integration',
      kind: 'freelance',
      tier: 3,
      titles: ['Connect the systems at {target}', 'Wire {target} together', 'Integrate the tools at {target}'],
      descs: [
        '{target} bought five different software products that refuse to speak to each other, so their staff re-type the same data five times a day. Build the integration layer that makes them one system. Invisible work, enormous payoff.',
        'Make {target}\'s ordering system talk to their inventory talk to their accounting, so a sale in one place updates everywhere. Tedious plumbing, real engineering, and a client who\'ll wonder how they lived without it.',
        '{target} runs on a dozen tools held together by copy-paste and prayer. Design the integrations, build them robust, and hand back the hours their team was losing to typing the same thing twice.',
      ],
      targets: ['a growing e-tailer', 'a distribution company', 'a multi-location clinic', 'a services firm'],
      clients: ['an operations director', 'a frustrated IT lead', 'a founder scaling up', 'a department head'],
      skills: ['programming', 'networking'],
      dc: [16, 18],
      hours: [9, 15],
      pay: [140, 300],
      heat: [0, 0],
      cred: [0, 0],
      available: { var: 'w.broadband', gte: 1 },
    },
    {
      id: 'f3_call_center',
      kind: 'freelance',
      tier: 3,
      titles: ['Build the call routing for {target}', 'Phone system overhaul: {target}', 'Wire the phones at {target}'],
      descs: [
        '{target} is expanding a phone operation and needs real call routing: queues, menus, recording, the reports that tell them why customers hang up. You\'ve seen enough phone systems from the inside to build a good one. The rate reflects the specialty.',
        'Design {target}\'s new phone infrastructure from the ground up — extensions, voicemail, the auto-attendant nobody will navigate correctly. Serious systems work for a client who lives and dies by the phones.',
        '{target}\'s calls drop, misroute, and vanish into voicemail purgatory. Rebuild the whole system, wire it right, and give a phone-dependent business the reliability it\'s been begging for.',
      ],
      targets: ['a customer-service operation', 'a medical answering service', 'a sales floor', 'a dispatch office'],
      clients: ['an operations manager', 'a call-center director', 'a small-business owner', 'a facilities lead'],
      skills: ['networking', 'systems'],
      dc: [15, 18],
      hours: [9, 16],
      pay: [140, 310],
      heat: [0, 0],
      cred: [0, 0],
      available: { jobTrack: ['sysadmin', 'network', 'support'] },
    },

    // ─────────────────────────── TIER 4 ────────────────────────────
    {
      id: 'f4_saas_rescue',
      kind: 'freelance',
      tier: 4,
      titles: ['Rescue the launch at {target}', 'Fix the platform at {target}', 'Save {target}\'s product'],
      descs: [
        '{target} launched a web product that\'s falling over under its own users, and every hour it\'s down is money and reputation gone. Come in senior, find the fires, put them out, and rebuild the parts that were never going to hold. The rate reflects the emergency.',
        '{target}\'s big launch went viral and then went down. Diagnose the architecture, fix what\'s breaking, and re-engineer it to survive success. High pressure, high visibility, high pay.',
        '{target} shipped something people actually want and now it\'s buckling. Be the senior hand who stabilizes it: the database, the caching, the whole strained machine. Save the launch, name your rate.',
      ],
      targets: ['a surprise-hit web service', 'a funded startup', 'an overwhelmed marketplace', 'a viral app'],
      clients: ['a panicking founder', 'a VP of engineering', 'a technical cofounder over their head', 'an investor demanding answers'],
      skills: ['programming', 'systems'],
      dc: [18, 21],
      hours: [11, 17],
      pay: [280, 780],
      heat: [0, 0],
      cred: [0, 0],
      available: { var: 'w.broadband', gte: 1 },
    },
    {
      id: 'f4_compliance',
      kind: 'freelance',
      tier: 4,
      titles: ['Get {target} audit-ready', 'Lead compliance for {target}', 'Certify the systems at {target}'],
      descs: [
        '{target} landed a client (or a regulator) who demands a real security-and-controls audit, and they are nowhere near ready. Assess the gap, build the controls, write the documentation nobody wants to write, and get them across the line. Specialist, above-board, well paid.',
        'A regulated engagement: get {target}\'s systems, policies, and paper trail into shape for a formal audit. You know exactly where bodies get buried because you\'ve buried a few. Sell that knowledge in daylight.',
        '{target} is failing an audit they can\'t afford to fail. Come in, fix the controls, document everything to the standard, and shepherd a terrified company through certification. The fee matches the stakes.',
      ],
      targets: ['a payments firm', 'a healthcare platform', 'a government contractor', 'a financial services company'],
      clients: ['a compliance officer', 'a cautious CTO', 'a nervous founder', 'a board under pressure'],
      skills: ['business', 'opsec'],
      dc: [18, 21],
      hours: [10, 16],
      pay: [235, 700],
      heat: [0, 0],
      cred: [0, 0],
      available: { any: [{ faction: 'fac.halcyon', gte: 20 }, { jobTrack: ['security', 'management'] }] },
    },
    {
      id: 'f4_mobile',
      kind: 'freelance',
      tier: 4,
      titles: ['Build the mobile app for {target}', 'Put {target} in a pocket', 'Ship {target}\'s app'],
      descs: [
        'Everyone suddenly has a smartphone and {target} wants an app before their competitor does. Design it, build it, wrestle it through the approval process, and ride the very front of a very new wave. Rare skill, brand-new market, a rate to match.',
        '{target} is convinced the future is in everyone\'s pocket (they\'re right) and needs a senior hand to build their first mobile app properly. New platform, real engineering, and a client willing to pay for the pioneer.',
        '{target} watched their whole industry go mobile overnight and panicked. Build them an app that actually works, teach them what the store expects, and get them onto the small screen before it\'s too late.',
      ],
      targets: ['a retail chain going digital', 'a media brand', 'a services company', 'a scrappy startup'],
      clients: ['a trend-driven CEO', 'a product manager', 'a first-mover founder', 'a marketing VP with budget'],
      skills: ['programming'],
      dc: [19, 22],
      hours: [11, 18],
      pay: [310, 780],
      heat: [0, 0],
      cred: [0, 0],
      available: { all: [{ day: true, gte: Y2008 }, { var: 'w.broadband', gte: 2 }] },
    },

    // ─────────────────────────── TIER 5 ────────────────────────────
    {
      id: 'f5_merger',
      kind: 'freelance',
      tier: 5,
      titles: ['Merge the systems for {target}', 'Integrate the acquisition at {target}', 'Unify {target}'],
      descs: [
        '{target} just bought a competitor and now runs two of everything that hate each other — two email systems, two databases, two cultures encoded in software. Lead the integration, keep the business running through it, and take a contract that reflects the sheer weight of the job.',
        'A merger left {target} with duplicated, incompatible everything. Architect the unification, migrate without losing a customer, and referee the political war over whose system "wins." Enormous scope, executive rate.',
        '{target} closed a deal the bankers loved and the engineers dread. Be the person who actually makes two companies into one system. Get it right and your name opens every boardroom in the city.',
      ],
      targets: ['a merged bank', 'a consolidated retailer', 'a healthcare network', 'a rolled-up services firm'],
      clients: ['a chief information officer', 'an integration program lead', 'a private-equity operating partner', 'a post-merger executive'],
      skills: ['systems', 'business'],
      dc: [21, 24],
      hours: [11, 18],
      pay: [780, 1460],
      heat: [0, 0],
      cred: [0, 0],
      available: { var: 'w.broadband', gte: 2 },
    },
    {
      id: 'f5_disaster_recovery',
      kind: 'freelance',
      tier: 5,
      titles: ['Architect disaster recovery for {target}', 'Make {target} unkillable', 'Build the failover for {target}'],
      descs: [
        '{target} finally understood that "it went down" can mean "we\'re out of business" and wants infrastructure that survives fire, flood, and a backhoe through the fiber. Design full disaster recovery — redundant sites, tested failover, the works. Once-in-a-career engineering, priced for it.',
        'A near-catastrophe convinced {target}\'s board to fund real resilience. Architect the redundant, geographically-split, actually-tested system that keeps them alive through anything. The rate matches the responsibility.',
        '{target} carries too much of the city on its systems to ever go dark. Build them true disaster recovery — the invisible machine that means a failure is a shrug instead of a headline. Serious money for serious peace of mind.',
      ],
      targets: ['a regional bank', 'a hospital network', 'a telecom', 'a critical logistics operation'],
      clients: ['a VP of infrastructure', 'a chief risk officer', 'a program director', 'a board mandate'],
      skills: ['networking', 'systems'],
      dc: [21, 24],
      hours: [11, 18],
      pay: [780, 1460],
      heat: [0, 0],
      cred: [0, 0],
      available: { var: 'w.broadband', gte: 2 },
    },
    {
      id: 'f5_ipo_readiness',
      kind: 'freelance',
      tier: 5,
      titles: ['Get {target} IPO-ready', 'Harden {target} for the offering', 'Scale {target} for the public markets'],
      descs: [
        '{target} is going public and their technology has to withstand the scrutiny of bankers, auditors, and a market that punishes every outage in real dollars. Lead the readiness: scale it, secure it, document it to a standard it has never met. The most consequential freelance there is, paid accordingly.',
        'A company on the runway to an IPO, {target}, needs a proven leader to make sure the systems don\'t embarrass them on the biggest day of the company\'s life. Executive-grade engineering and judgment, executive-grade rate.',
        '{target}\'s offering is months away and the diligence is going to find everything. Fix it first: the scale, the controls, the paper trail. Be the reason the road show goes smoothly, and never want for work again.',
      ],
      targets: ['a hot local startup', 'a scaling tech firm', 'a growth-stage company', 'a soon-to-be-public brand'],
      clients: ['a chief financial officer', 'a founder-CEO', 'a board of directors', 'a VP prepping the S-1'],
      skills: ['business', 'programming'],
      dc: [21, 24],
      hours: [11, 18],
      pay: [880, 1460],
      heat: [0, 0],
      cred: [0, 0],
      available: { var: 'w.broadband', gte: 1 },
    },
  ],
})
