import { defineContent } from '@/engine/registry'

/**
 * ECON — Procedural FREELANCE contract templates (the legit gig board). Websites, database
 * fixes, scripts, IT support, buildouts. Freelance work carries no heat and no cred; it pays,
 * trains skills, and — for the neighborhood jobs — earns a little goodwill with the Row.
 * Tiers gate on programming/business (engine `FREELANCE_TIERS`).
 *
 * Weekly-turn sizing: gigs are short so a full queue finishes 2–4 per turn on a few Freelance hours a
 * day; higher tiers pay more per hour rather than taking weeks each:
 *   t1 ~4–13 h $20–65 · t2 ~6–14 h $50–145 · t3 ~9–16 h $140–320 · t4 ~10–18 h $235–780 ·
 *   t5 ~11–18 h $780–1,460
 */
export default defineContent({
  contractTemplates: [
    // ─────────────────────────── TIER 1 ────────────────────────────
    {
      id: 'f1_website',
      kind: 'freelance',
      tier: 1,
      titles: ['Build a website for {target}', 'Homepage for {target}', 'Get {target} online'],
      descs: [
        '{target} wants a website "like the big companies have" and has a budget of roughly one nice dinner. Table layout, a hit counter, an under-construction GIF they specifically request. Charming, honest work.',
        'Put {target} on the web for the first time. They will email you the logo as a photograph of a printout. You will make it look fine anyway.',
        '{target} heard the internet is important. Build them three pages, teach them what a browser is, and collect a check written in careful cursive.',
      ],
      targets: ['a corner bakery', 'a plumber', 'a nail salon', 'a martial-arts dojo', "a barber shop"],
      clients: ['a first-time small-business owner', 'a friendly neighbor', 'a retiree with a side hustle', 'a hopeful shopkeeper'],
      skills: ['programming'],
      dc: [8, 11],
      hours: [6, 12],
      pay: [25, 65],
      heat: [0, 0],
      cred: [0, 0],
      rep: { 'fac.hood': 1 },
    },
    {
      id: 'f1_pc_fix',
      kind: 'freelance',
      tier: 1,
      titles: ['Fix {target}\'s computer', 'House call: {target}', 'Rescue {target}\'s PC'],
      descs: [
        '{target}\'s home PC "stopped working." It is, as always, full of toolbars, pop-ups, and a wallpaper of a beach they\'ve never visited. Clean it, speed it up, leave a hero.',
        '{target} unplugged something and now nothing works. Drive over, plug it back in, do not tell them that was the whole problem, charge a fair rate.',
        'The family computer at {target} is groaning under a decade of well-meaning mistakes. Fix it and you\'ll be the person they call forever. That\'s the deal, and it\'s a good one.',
      ],
      targets: ['a grandmother', 'a church group', 'a busy dad', 'a neighbor down the block', 'a retired teacher'],
      clients: ['a grateful neighbor', 'a family friend', 'a word-of-mouth referral', 'a very patient client'],
      skills: ['hardware', 'systems'],
      dc: [8, 10],
      hours: [4, 9],
      pay: [20, 50],
      heat: [0, 0],
      cred: [0, 0],
      rep: { 'fac.hood': 1 },
    },
    {
      id: 'f1_data_entry',
      kind: 'freelance',
      tier: 1,
      titles: ['Data entry for {target}', 'Digitize {target}\'s records', 'Spreadsheet work for {target}'],
      descs: [
        '{target} has a filing cabinet and a dream of a spreadsheet. Type it all in, make the columns line up, and collect an hourly rate that respects neither your time nor your soul. Rent is rent.',
        'Turn {target}\'s shoebox of receipts into a clean ledger. Dull, easy, and the client will be genuinely moved by your competence.',
        '{target} needs a decade of paper records keyed into the computer before the auditor comes. Mind-numbing, but the money is steady and the deadline is soft.',
      ],
      targets: ['a small charity', 'a landlord', 'an accountant', 'a doctor\'s office', 'a used bookstore'],
      clients: ['an overwhelmed office manager', 'a sole proprietor', 'a nonprofit director', 'a bookkeeper'],
      skills: ['business'],
      dc: [8, 10],
      hours: [7, 13],
      pay: [20, 60],
      heat: [0, 0],
      cred: [0, 0],
    },
    {
      id: 'f1_email_setup',
      kind: 'freelance',
      tier: 1,
      titles: ['Set up email for {target}', 'Get {target} connected', 'Wire up {target}'],
      descs: [
        '{target} wants email addresses that say their company name instead of the free provider. Configure the accounts, teach three people what "compose" means, escape before the fourth arrives.',
        'Connect {target}\'s two computers so they can share a printer, an act they consider indistinguishable from magic. String the cable, name the workgroup, accept the coffee.',
        '{target} got a fax-modem and no idea what to do with it. Set up their connection, their inbox, and their expectations. Simple money.',
      ],
      targets: ['an insurance agent', 'a small law office', 'a real-estate agent', 'a contractor', 'a florist'],
      clients: ['a non-technical professional', 'a two-person office', 'a solo agent', 'a small partnership'],
      skills: ['networking'],
      dc: [9, 11],
      hours: [5, 9],
      pay: [25, 60],
      heat: [0, 0],
      cred: [0, 0],
    },
    {
      id: 'f1_banner',
      kind: 'freelance',
      tier: 1,
      titles: ['Design a banner for {target}', 'Graphics for {target}', 'Make {target} look good'],
      descs: [
        '{target} wants an animated banner for their homepage with "more flames." Fire up the image editor, make something gloriously of-the-era, and resist every instinct toward taste.',
        'Build {target} a set of buttons, a marquee, and a background tile that does not induce a migraine. A small miracle they will underpay for happily.',
        '{target} saw a cool website and wants theirs to look like that. Deliver spinning logos and a guestbook. Everyone leaves happy.',
      ],
      targets: ['a garage band', 'a comic shop', 'a tattoo parlor', 'a skate shop', 'a wedding photographer'],
      clients: ['a creative type', 'a shop owner with vision', 'a hobbyist', 'a very online teenager\'s parent'],
      skills: ['programming'],
      dc: [8, 10],
      hours: [4, 9],
      pay: [20, 50],
      heat: [0, 0],
      cred: [0, 0],
    },
    {
      id: 'f1_virus_cleanup',
      kind: 'freelance',
      tier: 1,
      titles: ['Clean the virus off {target}', 'Malware removal: {target}', 'Disinfect {target}'],
      descs: [
        '{target} clicked "You\'ve Won!" and now the machine dials premium numbers by itself. Clean it out, install something to stop the next one, and give the gentle lecture. They will not listen.',
        'A pop-up storm has taken {target}\'s computer hostage. Remove the junk, explain what a link is, and leave the number of someone patient. That someone is now you.',
        '{target}\'s PC is so infected it has opinions. Scrub it down to something usable and accept payment in gratitude and a plate of cookies, plus cash.',
      ],
      targets: ['a teenager\'s parents', 'a home office', 'a small shop', 'an elderly couple', 'a college roommate'],
      clients: ['a frazzled parent', 'a self-employed client', 'a referral from a happy customer', 'a neighbor in distress'],
      skills: ['systems', 'hardware'],
      dc: [9, 12],
      hours: [5, 9],
      pay: [25, 65],
      heat: [0, 0],
      cred: [0, 0],
      rep: { 'fac.hood': 1 },
    },

    // ─────────────────────────── TIER 2 ────────────────────────────
    {
      id: 'f2_ecommerce',
      kind: 'freelance',
      tier: 2,
      titles: ['Build a store for {target}', 'Online shop for {target}', 'Get {target} selling online'],
      descs: [
        '{target} wants to sell their products online with a real shopping cart and a way to take cards. Now that the pipes are fat enough to matter, this is a serious build — and a serious check.',
        'Set up {target} with a catalog, a cart, and a payment gateway that won\'t lose anyone\'s money. The client\'s expectations are enormous; so, gratifyingly, is the budget.',
        '{target} sees their competitors selling online and wants in yesterday. Build the store, wire the payments, and become the reason their business doubles.',
      ],
      targets: ['a specialty grocer', 'a craft supplier', 'a record store', 'an outdoor-gear shop', 'a small publisher'],
      clients: ['an ambitious owner', 'a family business going digital', 'a second-generation shopkeeper', 'a hopeful entrepreneur'],
      skills: ['programming', 'business'],
      dc: [13, 15],
      hours: [8, 14],
      pay: [70, 145],
      heat: [0, 0],
      cred: [0, 0],
      available: { var: 'w.broadband', gte: 1 },
    },
    {
      id: 'f2_db_fix',
      kind: 'freelance',
      tier: 2,
      titles: ['Fix the database at {target}', 'Rescue {target}\'s records', 'Untangle {target}\'s data'],
      descs: [
        '{target}\'s inventory database "went weird" and now it swears they have negative eleven thousand of an item. Find the corruption, fix the schema, and restore the client\'s faith in numbers.',
        'The homegrown database at {target} was built by a nephew who has since moved away. Make it work, document it, and gently future-proof it against the next nephew.',
        '{target} is one crash away from losing their whole customer history. Repair it, back it up properly, and be the calm in their small catastrophe.',
      ],
      targets: ['a wholesale distributor', 'a dental practice', 'a parts supplier', 'a membership club', 'a tour operator'],
      clients: ['a panicking office manager', 'a small business owner', 'a practice administrator', 'an operations lead'],
      skills: ['systems', 'programming'],
      dc: [12, 15],
      hours: [7, 13],
      pay: [60, 140],
      heat: [0, 0],
      cred: [0, 0],
    },
    {
      id: 'f2_office_lan',
      kind: 'freelance',
      tier: 2,
      titles: ['Wire the office at {target}', 'Build a LAN for {target}', 'Network {target}'],
      descs: [
        '{target} is moving into a new office and needs every desk connected, a shared drive, and a printer nobody has to fight. Run the cable, stand up the server, hand them a network that just works.',
        'Design and build {target}\'s office network from bare walls: switches, cabling, a file server, the works. Real infrastructure, real satisfaction, real invoice.',
        '{target} outgrew its two-computer setup. Give them a proper LAN, shared storage, and the ability to grow without calling you every week. (They will call you every week.)',
      ],
      targets: ['an architecture firm', 'a growing agency', 'a medical clinic', 'an engineering shop', 'a design studio'],
      clients: ['an office manager', 'a small-firm partner', 'a practice owner', 'a startup founder'],
      skills: ['networking', 'hardware'],
      dc: [13, 15],
      hours: [8, 14],
      pay: [90, 145],
      heat: [0, 0],
      cred: [0, 0],
    },
    {
      id: 'f2_automation',
      kind: 'freelance',
      tier: 2,
      titles: ['Write a script for {target}', 'Automate {target}', 'Save {target} some hours'],
      descs: [
        '{target} does a mind-numbing task by hand every week — renaming files, merging reports, reformatting the same spreadsheet. Write the tool that does it in a keystroke and become quietly legendary.',
        'Someone at {target} spends every Friday on a job a script could do in a second. Write the script, watch their face, collect the fee for handing back their weekends.',
        '{target} needs a batch process that turns their messy exports into clean imports. Build it, document it, and make the tedium disappear.',
      ],
      targets: ['a mailing house', 'a small newsroom', 'a logistics office', 'a research lab', 'an accounting firm'],
      clients: ['a swamped analyst', 'an operations manager', 'a data-weary clerk', 'a small-team lead'],
      skills: ['programming'],
      dc: [12, 15],
      hours: [6, 12],
      pay: [50, 135],
      heat: [0, 0],
      cred: [0, 0],
    },
    {
      id: 'f2_it_support',
      kind: 'freelance',
      tier: 2,
      titles: ['IT support retainer for {target}', 'On-call for {target}', 'Keep {target} running'],
      descs: [
        '{target} wants someone to call when things break, which is constantly. Set up their systems right, then get paid to answer the phone patiently while they describe an error message they didn\'t read.',
        'A monthly retainer with {target}: keep the machines patched, the backups running, and the staff from clicking the wrong thing. Steady, unglamorous, dependable money.',
        '{target} is too small for an IT department and too big to keep guessing. Be their part-time department. The work is easy; the value is the trust.',
      ],
      targets: ['a small law firm', 'a nonprofit', 'a dental office', 'a boutique agency', 'a family business'],
      clients: ['a managing partner', 'an executive director', 'a practice manager', 'an owner-operator'],
      skills: ['systems', 'networking'],
      dc: [12, 14],
      hours: [7, 13],
      pay: [65, 140],
      heat: [0, 0],
      cred: [0, 0],
    },
    {
      id: 'f2_pos',
      kind: 'freelance',
      tier: 2,
      titles: ['Set up point-of-sale at {target}', 'Register system for {target}', 'Modernize the checkout at {target}'],
      descs: [
        '{target} still rings up sales on a machine that prints on a roll of paper the width of a receipt for a reason nobody remembers. Install a real POS, wire the drawer and scanner, train the staff who fear it.',
        'Replace {target}\'s ancient register with a system that tracks inventory as it sells. The hardware is fiddly, the software is worse, and the payoff is a shop that finally knows what it has.',
        '{target} wants barcodes, a card reader, and end-of-day reports that add up. Build it, test it against a hundred weird edge cases, and hand over a checkout that works.',
      ],
      targets: ['a hardware store', 'a cafe', 'a boutique', 'a deli', 'a garden center'],
      clients: ['a hands-on owner', 'a franchise operator', 'a shopkeeper', 'a small-chain manager'],
      skills: ['hardware', 'systems'],
      dc: [12, 15],
      hours: [7, 12],
      pay: [70, 145],
      heat: [0, 0],
      cred: [0, 0],
    },

    // ─────────────────────────── TIER 3 ────────────────────────────
    {
      id: 'f3_web_app',
      kind: 'freelance',
      tier: 3,
      titles: ['Build a web application for {target}', 'Custom system for {target}', 'Develop {target}\'s platform'],
      descs: [
        '{target} has outgrown spreadsheets and needs a real web application — logins, a database, reports, the lot. This is a serious build with a serious spec, and finally the kind of gig that pays like a job.',
        'Design and build {target} a custom web tool that runs a core part of their business. Months of work, a real architecture, and a client who will refer you for years if you get it right.',
        '{target} wants to replace three off-the-shelf products with one thing that actually fits how they work. Scope it, build it, ship it. Career-building freelance.',
      ],
      targets: ['a property manager', 'a staffing agency', 'a regional nonprofit', 'a distribution company', 'a clinic network'],
      clients: ['an operations director', 'a founder with funding', 'a department head', 'a growing-company owner'],
      skills: ['programming'],
      dc: [15, 18],
      hours: [9, 16],
      pay: [140, 320],
      heat: [0, 0],
      cred: [0, 0],
      available: { var: 'w.broadband', gte: 1 },
    },
    {
      id: 'f3_migration',
      kind: 'freelance',
      tier: 3,
      titles: ['Migrate {target}\'s servers', 'Move {target} to new hardware', 'Rebuild {target}\'s systems'],
      descs: [
        '{target} is running its whole business on a server under a desk that is one power surge from disaster. Plan the migration, move it all with zero data loss, and let them sleep for the first time in years.',
        'Move {target} off its dying infrastructure onto something modern and supported, over a weekend, without anyone noticing on Monday. High stakes, high reward, no room for error.',
        '{target}\'s systems have grown into a tangle nobody fully understands. Map it, migrate it cleanly, and document it so the next person isn\'t you at 3 a.m.',
      ],
      targets: ['a manufacturer', 'a regional retailer', 'a hospital department', 'a logistics firm', 'a media company'],
      clients: ['an IT director', 'an operations VP', 'a facilities manager', 'a nervous CFO'],
      skills: ['systems', 'networking'],
      dc: [15, 18],
      hours: [10, 16],
      pay: [160, 320],
      heat: [0, 0],
      cred: [0, 0],
    },
    {
      id: 'f3_db_design',
      kind: 'freelance',
      tier: 3,
      titles: ['Design a database for {target}', 'Data architecture for {target}', 'Model {target}\'s business'],
      descs: [
        '{target} needs its entire operation modeled properly — customers, orders, inventory, the works — in a database that will scale for a decade. Get the schema right and everything they build on it just works.',
        'Design the data layer for {target} from scratch: normalized, indexed, documented, and built to survive the features they haven\'t thought of yet. The invisible work that makes everything else possible.',
        '{target} has been bolting fields onto a spreadsheet for years and it finally broke. Design the real thing, migrate the mess into it, and give them a foundation worth building on.',
      ],
      targets: ['an e-commerce company', 'a subscription service', 'a healthcare startup', 'a fintech firm', 'a marketplace'],
      clients: ['a technical founder', 'a product manager', 'a lead engineer', 'a data-hungry executive'],
      skills: ['programming', 'business'],
      dc: [16, 18],
      hours: [9, 15],
      pay: [140, 300],
      heat: [0, 0],
      cred: [0, 0],
    },
    {
      id: 'f3_security_audit',
      kind: 'freelance',
      tier: 3,
      titles: ['Security audit for {target}', 'Harden {target}', 'Assess the risk at {target}'],
      descs: [
        '{target} wants a professional, above-board security review before their big client demands one. Test their defenses, write the honest report, and help them fix what you find. Poacher-turned-gamekeeper money.',
        'A legitimate engagement: probe {target}\'s systems with permission, document every weakness, and hand them a roadmap to fix it. Everything you learned in the dark, sold in the light.',
        '{target} got scared by a headline and wants to know how exposed they are. Audit them thoroughly, deliver the bad news gently, and become their trusted advisor.',
      ],
      targets: ['a credit union', 'a law firm', 'a healthcare provider', 'a small bank', 'a government contractor'],
      clients: ['a compliance officer', 'a cautious executive', 'an IT director', 'a board member'],
      skills: ['opsec', 'systems'],
      dc: [16, 18],
      hours: [9, 14],
      pay: [180, 320],
      heat: [0, 0],
      cred: [0, 0],
    },
    {
      id: 'f3_intranet',
      kind: 'freelance',
      tier: 3,
      titles: ['Build an intranet for {target}', 'Internal portal for {target}', 'Connect {target}\'s offices'],
      descs: [
        '{target} has three offices that email each other spreadsheets and hope. Build them an intranet — shared documents, directories, a place for the company to actually be one company. Real, satisfying systems work.',
        'Stand up {target}\'s internal portal: single sign-on, shared calendars, document management, the digital town square of a growing firm. Months of work, a client for life.',
        '{target} wants everything internal in one place, secured and searchable. Design it, build it, and watch a scattered company start to feel like a team.',
      ],
      targets: ['a multi-branch firm', 'a regional chain', 'a consultancy', 'a nonprofit network', 'a school district'],
      clients: ['a communications director', 'an operations manager', 'an IT lead', 'a general manager'],
      skills: ['networking', 'programming'],
      dc: [15, 18],
      hours: [9, 15],
      pay: [140, 300],
      heat: [0, 0],
      cred: [0, 0],
      available: { var: 'w.broadband', gte: 1 },
    },

    // ─────────────────────────── TIER 4 ────────────────────────────
    {
      id: 'f4_platform',
      kind: 'freelance',
      tier: 4,
      titles: ['Build a platform for {target}', 'Lead the build at {target}', 'Ship {target}\'s product'],
      descs: [
        '{target} raised money and needs a real product built fast by someone who knows what they\'re doing. Architect it, build the core, and take a contractor rate that finally reflects a decade of practice.',
        'A funded startup, {target}, needs a senior hand to build the thing the deck promised investors. High expectations, high pressure, and a check that changes your year.',
        '{target} has the vision and the money and none of the engineering. Be the engineering. Design the platform, build it right, and hand off something that scales.',
      ],
      targets: ['a venture-backed startup', 'a spin-out company', 'a growth-stage firm', 'an ambitious agency', 'a new marketplace'],
      clients: ['a first-time founder', 'a product-focused CEO', 'a technical cofounder out of their depth', 'a startup board'],
      skills: ['programming', 'business'],
      dc: [18, 21],
      hours: [11, 17],
      pay: [280, 780],
      heat: [0, 0],
      cred: [0, 0],
      available: { var: 'w.broadband', gte: 1 },
    },
    {
      id: 'f4_infra',
      kind: 'freelance',
      tier: 4,
      titles: ['Build out infrastructure for {target}', 'Scale {target}', 'Engineer {target}\'s backbone'],
      descs: [
        '{target} is growing faster than its systems can handle and needs someone to build infrastructure that won\'t fall over at the worst moment. Design it, build it, make it boring in the best way.',
        'Architect and deploy {target}\'s next-generation infrastructure: redundant, monitored, and built to carry ten times their current load. Serious engineering for serious money.',
        '{target} keeps going down at peak times and losing real money each time. Rebuild the backbone so it never happens again, and name your rate.',
      ],
      targets: ['a busy online service', 'a regional ISP', 'a data-heavy startup', 'a media platform', 'a SaaS company'],
      clients: ['a VP of engineering', 'an infrastructure lead', 'a CTO under pressure', 'an operations director'],
      skills: ['networking', 'systems'],
      dc: [18, 21],
      hours: [11, 18],
      pay: [280, 780],
      heat: [0, 0],
      cred: [0, 0],
      available: { var: 'w.broadband', gte: 2 },
    },
    {
      id: 'f4_crypto_impl',
      kind: 'freelance',
      tier: 4,
      titles: ['Implement encryption for {target}', 'Secure the data at {target}', 'Build crypto for {target}'],
      descs: [
        '{target} handles data that legally must be protected and currently isn\'t. Design and implement the encryption properly — key management, the works — because getting this wrong is worse than doing nothing. Specialist money.',
        'A regulated client, {target}, needs cryptography built into their product by someone who actually understands it. Rare skill, rare rate, real responsibility.',
        '{target} got burned by a breach and wants their data locked down for real this time. Implement it correctly, document it for the auditors, and sleep well.',
      ],
      targets: ['a payments company', 'a healthcare platform', 'a legal-tech firm', 'a financial service', 'a records company'],
      clients: ['a compliance-driven CTO', 'a security officer', 'a cautious founder', 'a regulated-industry lead'],
      skills: ['cryptography', 'programming'],
      dc: [19, 21],
      hours: [11, 17],
      pay: [310, 780],
      heat: [0, 0],
      cred: [0, 0],
    },
    {
      id: 'f4_consulting',
      kind: 'freelance',
      tier: 4,
      titles: ['Consult for {target}', 'Advise {target}', 'Strategy engagement with {target}'],
      descs: [
        '{target}\'s leadership needs someone who has actually built things to tell them what\'s possible, what\'s a fantasy, and what their vendor is lying about. Charge for the years, not the hours.',
        'A high-end advisory gig: sit with {target}\'s executives, cut through the buzzwords, and design a technology strategy that survives contact with reality. The most lucrative kind of talking.',
        '{target} is about to spend a fortune on the wrong thing and needs an honest expert in the room. Be that expert. The fee reflects how much you\'ll save them.',
      ],
      targets: ['a mid-size company', 'a city agency', 'a hospital board', 'a manufacturing group', 'a retail chain'],
      clients: ['a CEO', 'a board of directors', 'a chief operating officer', 'a transformation committee'],
      skills: ['business', 'systems'],
      dc: [18, 21],
      hours: [10, 15],
      pay: [235, 700],
      heat: [0, 0],
      cred: [0, 0],
    },

    // ─────────────────────────── TIER 5 ────────────────────────────
    {
      id: 'f5_enterprise',
      kind: 'freelance',
      tier: 5,
      titles: ['Build the enterprise system for {target}', 'Deliver {target}\'s core platform', 'Lead the flagship build at {target}'],
      descs: [
        '{target} is betting the company on a single enormous system and needs a proven lead to deliver it. Architect the whole thing, run the build, and take the kind of contract that changes what you can afford. Everything you\'ve learned, all at once.',
        'A flagship engagement: design and deliver the system {target}\'s entire future runs on. Huge scope, huge stakes, and a payout that ends the question of whether you needed a day job.',
        '{target} tried this build twice with other firms and failed twice. Be the third and last. Get it right and your name opens every door in the city.',
      ],
      targets: ['a national retailer', 'a healthcare network', 'a financial institution', 'a logistics giant', 'a telecom'],
      clients: ['a chief information officer', 'a transformation executive', 'a program director', 'a board mandate'],
      skills: ['programming', 'business'],
      dc: [21, 24],
      hours: [11, 18],
      pay: [780, 1460],
      heat: [0, 0],
      cred: [0, 0],
      available: { var: 'w.broadband', gte: 2 },
    },
    {
      id: 'f5_datacenter_design',
      kind: 'freelance',
      tier: 5,
      titles: ['Design the data center for {target}', 'Architect {target}\'s facility', 'Build {target}\'s campus network'],
      descs: [
        '{target} is building a data center from the concrete up and needs someone to design the network, the redundancy, and the operations that will run it for a decade. Once-in-a-career work, priced accordingly.',
        'Design the entire technical facility for {target}: power, cooling, network, failover, monitoring — the invisible machine that keeps a whole business breathing. The rate matches the responsibility.',
        '{target} is moving into the old mill district and turning it into a data campus. Architect it right and you build a piece of the city\'s future — for better or worse.',
      ],
      targets: ['a hosting company', 'a cloud provider', 'a bank', 'a telecom', 'a research institution'],
      clients: ['a facilities director', 'a VP of infrastructure', 'a program lead', 'a chief technology officer'],
      skills: ['networking', 'systems'],
      dc: [21, 24],
      hours: [11, 18],
      pay: [780, 1460],
      heat: [0, 0],
      cred: [0, 0],
      available: { var: 'w.broadband', gte: 2 },
    },
    {
      id: 'f5_cto',
      kind: 'freelance',
      tier: 5,
      titles: ['Fractional CTO for {target}', 'Run technology for {target}', 'Lead {target} as interim CTO'],
      descs: [
        '{target} needs a technology leader now and can\'t hire fast enough, so they\'ll rent yours. Set the strategy, build the team, ship the roadmap — all the weight of the title, none of the badge. The rate is executive.',
        'A funded company, {target}, needs an interim CTO to steady the ship and build for scale. Months of leadership at a rate that reflects a decade of hard-won judgment.',
        '{target}\'s last technical leader left a mess and a good team. Come in, fix the strategy, keep the people, and hand back a company that runs. The most valuable freelance there is.',
      ],
      targets: ['a growth-stage startup', 'a scaling company', 'a private-equity portfolio firm', 'a turnaround', 'an ambitious agency'],
      clients: ['a founder', 'a board of directors', 'a private-equity partner', 'a chief executive'],
      skills: ['business', 'programming'],
      dc: [21, 24],
      hours: [11, 18],
      pay: [880, 1460],
      heat: [0, 0],
      cred: [0, 0],
      available: { var: 'w.broadband', gte: 1 },
    },
  ],
})
