import { defineContent } from '@/engine/registry'

/**
 * ECON — Self-study / certification courses. Buy a course, set it as your study focus, and study
 * hours pour targeted XP into the course's skill(s) (16–30 XP/hour) until the hours are met; on
 * completion you get a certificate flag other systems can read. All cert bodies are invented.
 * Priced $80–1500 with 30–200 study hours.
 */
export default defineContent({
  courses: [
    {
      id: 'course_pc_medic',
      name: 'PC Medic Certification',
      desc: 'A weekend-warrior hardware course: diagnose, swap, reseat, and stop being afraid of the inside of a case. The exam is genuinely fixing a dead machine.',
      price: 120,
      hours: 20,
      skillXp: { hardware: 24 },
      onComplete: [{ flag: 'cert.pc_medic' }],
    },
    {
      id: 'course_netweave_assoc',
      name: 'NetWeave Associate',
      desc: 'The entry networking cert everyone lists on a résumé. Subnets, cabling, the seven layers you will forget and re-learn forever. Employers love the three letters after your name.',
      price: 350,
      hours: 35,
      skillXp: { networking: 22 },
      onComplete: [{ flag: 'cert.network_plus_like' }],
    },
    {
      id: 'course_netweave_pro',
      name: 'NetWeave Professional',
      desc: 'The advanced track: routing, switching, and designing a network that survives contact with actual users. Long, dry, and worth real money on the ladder.',
      price: 900,
      hours: 70,
      skillXp: { networking: 26, systems: 10 },
      req: { flag: 'cert.network_plus_like' },
      onComplete: [{ flag: 'cert.netweave_pro' }],
    },
    {
      id: 'course_syskeeper',
      name: 'SysKeeper Admin Track',
      desc: 'Systems administration from the ground up: users, permissions, backups, and the grim art of keeping a server alive that everyone forgets about until it dies.',
      price: 500,
      hours: 45,
      skillXp: { systems: 24, networking: 8 },
      onComplete: [{ flag: 'cert.syskeeper' }],
    },
    {
      id: 'course_structured_prog',
      name: 'Structured Programming Fundamentals',
      desc: 'Loops, functions, and why global variables will find you in your sleep. The correspondence course that turns a copy-paster into a programmer.',
      price: 200,
      hours: 30,
      skillXp: { programming: 24 },
      onComplete: [{ flag: 'cert.structured_prog' }],
    },
    {
      id: 'course_data_structures',
      name: 'Data Structures by Correspondence',
      desc: 'Trees, hashes, and the deep satisfaction of the right container for the job. Comes with a workbook you will actually do, because the problems are beautiful.',
      price: 450,
      hours: 55,
      skillXp: { programming: 28 },
      req: { flag: 'cert.structured_prog' },
      onComplete: [{ flag: 'cert.data_structures' }],
    },
    {
      id: 'course_ciphercraft',
      name: 'CipherCraft Fundamentals',
      desc: 'A cryptography course for people who like the math and the paranoia in equal measure. By the end you trust nothing and can prove why.',
      price: 550,
      hours: 60,
      skillXp: { cryptography: 26 },
      onComplete: [{ flag: 'cert.ciphercraft' }],
    },
    {
      id: 'course_greyhat',
      name: 'The GreyHat Correspondence Course',
      desc: 'A mail-order "ethical intrusion" course of dubious accreditation and excellent instincts, mailed in plain brown envelopes. Half of it is nonsense; the other half is dangerously good.',
      price: 300,
      hours: 40,
      skillXp: { intrusion: 24, opsec: 8 },
      onComplete: [{ flag: 'cert.greyhat' }],
    },
    {
      id: 'course_ghost_protocol',
      name: 'Operational Discretion',
      desc: 'A quiet course, taught quietly, on staying invisible: compartmentalization, clean habits, and never being the loudest person in a log file. The kind of thing you only appreciate after the raid.',
      price: 700,
      hours: 50,
      skillXp: { opsec: 26 },
      onComplete: [{ flag: 'cert.discretion' }],
    },
    {
      id: 'course_firewall',
      name: 'Perimeter & Firewall Basics',
      desc: 'How to build a wall and, incidentally, everything you need to know about the walls other people build. Defense taught by former offense.',
      price: 400,
      hours: 38,
      skillXp: { systems: 16, networking: 16 },
      onComplete: [{ flag: 'cert.firewall' }],
    },
    {
      id: 'course_cold_reading',
      name: 'The Sodium Row School of Cold Reading',
      desc: 'An evening class in the back of the pager shop, taught by a man who used to run a psychic hotline, on reading people fast and steering a conversation. Deeply unethical. Extremely useful.',
      price: 180,
      hours: 22,
      skillXp: { social: 26 },
      onComplete: [{ flag: 'cert.cold_reading' }],
    },
    {
      id: 'course_public_speaking',
      name: 'Public Speaking for the Terminally Shy',
      desc: 'For the kind of person who can talk a mainframe into anything and a human into nothing. Small room, kind teacher, real progress.',
      price: 150,
      hours: 20,
      skillXp: { social: 22 },
      onComplete: [{ flag: 'cert.public_speaking' }],
    },
    {
      id: 'course_bootstrapping',
      name: 'Small Business Bootstrapping',
      desc: 'How to turn a skill into an invoice: pricing, contracts, taxes, and the terrible truth that being good is only half the job. The community-college class that pays for itself.',
      price: 250,
      hours: 28,
      skillXp: { business: 24 },
      onComplete: [{ flag: 'cert.bootstrapping' }],
    },
    {
      id: 'course_financial_modeling',
      name: 'Financial Modeling in a Spreadsheet',
      desc: 'Cash flow, projections, and making a fictional future look convincing in a grid of cells. Equally useful for a startup pitch and for figuring out if you can make rent.',
      price: 600,
      hours: 48,
      skillXp: { business: 26 },
      req: { flag: 'cert.bootstrapping' },
      onComplete: [{ flag: 'cert.financial_modeling' }],
    },
    {
      id: 'course_home_fitness',
      name: 'Iron & Cardio: The Home Program',
      desc: 'A VHS-and-workbook program for building a body that can survive a career spent in a chair. Aggressively upbeat. It works if you press play.',
      price: 80,
      hours: 15,
      skillXp: { fitness: 22 },
      onComplete: [{ flag: 'cert.home_fitness' }],
    },
    {
      id: 'course_security_architect',
      name: 'Certified Security Architect',
      desc: 'The capstone cert that opens the six-figure doors: threat modeling, secure design, and speaking fluently to executives who are terrified of you. Expensive, brutal, and the ticket to the top of the legit ladder.',
      price: 1500,
      hours: 100,
      skillXp: { opsec: 20, systems: 14, networking: 10 },
      req: { flag: 'cert.syskeeper' },
      onComplete: [{ flag: 'cert.security_architect' }],
    },
  ],
})
