import { dayOf } from '@/engine/calendar'
import { defineContent } from '@/engine/registry'

/**
 * ECON — Hardware. One equipped item per slot; the newest purchase auto-equips when its
 * `tier` is ≥ the currently equipped tier. The five engine START_ITEMS are defined here as
 * tier-0, price-0, `unique` starters (owned from character creation, never sold, raid-safe).
 * Later generations gate in by calendar date; network gear gates on the broadband rollout.
 */
export default defineContent({
  items: [
    // ── CPU (the whole beige box; tier = generation) ────────────────────────
    {
      id: 'beige_pc_p2',
      name: 'Beige Box (P2-class)',
      category: 'cpu',
      shop: 'computer',
      price: 0,
      tier: 0,
      unique: true,
      desc: 'A hand-me-down tower the color of old teeth. It boots. Mostly. The fan sounds like a small aircraft that has given up on its dreams.',
      mods: [],
    },
    {
      id: 'cpu_p3_450',
      name: 'Cyrene III / 800',
      category: 'cpu',
      shop: 'computer',
      price: 450,
      tier: 1,
      available: { day: true, gte: dayOf(2002, 0, 1) },
      desc: "A proper new tower. It's so fast you'll catch yourself just opening and closing folders to watch them snap.",
      mods: [
        { key: 'hack.speed', mult: 1.15 },
        { key: 'freelance.speed', mult: 1.1 },
        { key: 'crack.speed', mult: 1.15 },
      ],
    },
    {
      id: 'cpu_p4_800',
      name: 'Cyrene IV / 2.4',
      category: 'cpu',
      shop: 'computer',
      price: 800,
      tier: 2,
      available: { day: true, gte: dayOf(2003, 0, 1) },
      desc: 'Runs hot enough to dry your socks on. Compiles fall off the screen. You can feel the future in the exhaust vent.',
      mods: [
        { key: 'hack.speed', mult: 1.3 },
        { key: 'freelance.speed', mult: 1.2 },
        { key: 'crack.speed', mult: 1.3 },
      ],
    },
    {
      id: 'cpu_dual_700',
      name: 'Meridian Duo E2',
      category: 'cpu',
      shop: 'computer',
      price: 700,
      tier: 3,
      available: { day: true, gte: dayOf(2006, 0, 1) },
      desc: "Two cores. You can crack a hash and lose a Solitaire game at the same time, and you will.",
      mods: [
        { key: 'hack.speed', mult: 1.5 },
        { key: 'freelance.speed', mult: 1.35 },
        { key: 'crack.speed', mult: 1.5 },
      ],
    },
    {
      id: 'cpu_quad_900',
      name: 'Meridian Quad Q9',
      category: 'cpu',
      shop: 'computer',
      price: 900,
      tier: 4,
      available: { day: true, gte: dayOf(2009, 0, 1) },
      desc: 'Four cores, a heatsink the size of a fist, and a case window so everyone knows you spent the money. Silences a lot of arguments about who has the fastest rig.',
      mods: [
        { key: 'hack.speed', mult: 1.75 },
        { key: 'freelance.speed', mult: 1.55 },
        { key: 'crack.speed', mult: 1.75 },
      ],
    },

    // ── RAM ─────────────────────────────────────────────────────────────────
    {
      id: 'ram_64mb',
      name: '64 MB SDRAM',
      category: 'ram',
      shop: 'computer',
      price: 0,
      tier: 0,
      unique: true,
      desc: 'Enough memory to run the browser or the mail client. Not both. Choose your fighter.',
      mods: [],
    },
    {
      id: 'ram_128mb',
      name: '128 MB SDRAM',
      category: 'ram',
      shop: 'computer',
      price: 60,
      tier: 1,
      desc: 'Twice the RAM, half the swapping. The hard drive finally stops sounding like a coffee grinder.',
      mods: [
        { key: 'xp.programming', mult: 1.05 },
        { key: 'freelance.speed', mult: 1.05 },
      ],
    },
    {
      id: 'ram_256mb',
      name: '256 MB SDRAM',
      category: 'ram',
      shop: 'computer',
      price: 110,
      tier: 2,
      desc: 'You can leave the messenger open now. And the browser. And a text editor with your notes in it. Living large.',
      mods: [
        { key: 'xp.programming', mult: 1.1 },
        { key: 'hack.speed', mult: 1.08 },
        { key: 'freelance.speed', mult: 1.1 },
      ],
    },
    {
      id: 'ram_512mb',
      name: '512 MB DDR',
      category: 'ram',
      shop: 'computer',
      price: 160,
      tier: 3,
      available: { day: true, gte: dayOf(2003, 0, 1) },
      desc: 'The kind of headroom where you stop closing programs out of guilt.',
      mods: [
        { key: 'xp.programming', mult: 1.15 },
        { key: 'hack.speed', mult: 1.12 },
        { key: 'freelance.speed', mult: 1.12 },
      ],
    },
    {
      id: 'ram_1gb',
      name: '1 GB DDR',
      category: 'ram',
      shop: 'computer',
      price: 220,
      tier: 4,
      available: { day: true, gte: dayOf(2004, 0, 1) },
      desc: 'A gigabyte. Your dad still asks if that\'s "the big kind." Yes, Dad. It\'s the big kind.',
      mods: [
        { key: 'xp.programming', mult: 1.2 },
        { key: 'hack.speed', mult: 1.18 },
        { key: 'freelance.speed', mult: 1.18 },
      ],
    },
    {
      id: 'ram_4gb',
      name: '4 GB DDR2 kit',
      category: 'ram',
      shop: 'computer',
      price: 180,
      tier: 5,
      available: { day: true, gte: dayOf(2007, 0, 1) },
      desc: 'Prices finally fell off a cliff. Four gigs for the price of a night out. Buy it before someone raises them again.',
      mods: [
        { key: 'xp.programming', mult: 1.3 },
        { key: 'hack.speed', mult: 1.25 },
        { key: 'freelance.speed', mult: 1.25 },
      ],
    },

    // ── Storage ─────────────────────────────────────────────────────────────
    {
      id: 'hdd_4gb',
      name: '4 GB Hard Disk',
      category: 'storage',
      shop: 'computer',
      price: 0,
      tier: 0,
      unique: true,
      desc: 'Four gigs, ninety percent full of things you swear you\'ll sort out someday. It ticks when it thinks.',
      mods: [],
    },
    {
      id: 'hdd_20gb',
      name: '20 GB Hard Disk',
      category: 'storage',
      shop: 'computer',
      price: 90,
      tier: 1,
      desc: 'Room to breathe. Room for a whole shelf of burned CDs, dumped onto one quiet, spinning platter.',
      mods: [{ key: 'efficiency', mult: 1.02 }],
    },
    {
      id: 'hdd_80gb',
      name: '80 GB Hard Disk',
      category: 'storage',
      shop: 'computer',
      price: 140,
      tier: 2,
      desc: 'Enough space that you can keep your work and keep a copy of your work and still have room to lose track of both.',
      mods: [
        { key: 'efficiency', mult: 1.03 },
        { key: 'heat.decay', add: 0.04 },
      ],
    },
    {
      id: 'hdd_250gb',
      name: '250 GB Hard Disk',
      category: 'storage',
      shop: 'computer',
      price: 160,
      tier: 3,
      available: { day: true, gte: dayOf(2004, 0, 1) },
      desc: 'A quarter of a terabyte. Somewhere on it is a folder called "misc" that could end a marriage.',
      mods: [
        { key: 'efficiency', mult: 1.04 },
        { key: 'heat.decay', add: 0.08 },
      ],
    },
    {
      id: 'hdd_1tb',
      name: '1 TB Hard Disk',
      category: 'storage',
      shop: 'computer',
      price: 150,
      tier: 4,
      available: { day: true, gte: dayOf(2007, 0, 1) },
      desc: 'A terabyte. You could keep everything you ever touched and never delete a single log. Which is either safety or evidence, depending on the week.',
      mods: [
        { key: 'efficiency', mult: 1.06 },
        { key: 'heat.decay', add: 0.12 },
      ],
    },

    // ── Network (gates on the broadband rollout var `w.broadband`) ───────────
    {
      id: 'modem_33k',
      name: '33.6k Modem',
      category: 'network',
      shop: 'computer',
      price: 0,
      tier: 0,
      unique: true,
      desc: 'The handshake. That scream of static that means the whole world just opened up — right up until Mom picks up the kitchen phone.',
      mods: [],
    },
    {
      id: 'modem_56k',
      name: '56k Modem',
      category: 'network',
      shop: 'computer',
      price: 70,
      tier: 1,
      desc: "Never actually hits 56k. Hits 44k on a good night with the wind behind it, and you'll take it.",
      mods: [
        { key: 'hack.speed', mult: 1.05 },
        { key: 'trace', mult: 1.1 },
      ],
    },
    {
      id: 'net_isdn',
      name: 'ISDN Line',
      category: 'network',
      shop: 'computer',
      price: 250,
      tier: 2,
      upkeepPerDay: 2,
      available: { day: true, gte: dayOf(2002, 0, 1) },
      desc: 'Two bonded channels and a monthly bill that makes your eyes water. But you can be online and take a phone call. Sorcery.',
      mods: [
        { key: 'hack.speed', mult: 1.1 },
        { key: 'trace', mult: 1.2 },
      ],
    },
    {
      id: 'net_dsl',
      name: 'DSL Connection',
      category: 'network',
      shop: 'computer',
      price: 120,
      tier: 3,
      upkeepPerDay: 1.5,
      available: { var: 'w.broadband', gte: 1 },
      desc: 'Always on. No dialling, no handshake, no busy signal. The first time you leave it connected overnight it feels illegal.',
      mods: [
        { key: 'hack.speed', mult: 1.2 },
        { key: 'trace', mult: 1.35 },
      ],
    },
    {
      id: 'net_cable',
      name: 'Cable Broadband',
      category: 'network',
      shop: 'computer',
      price: 150,
      tier: 4,
      upkeepPerDay: 2,
      available: { var: 'w.broadband', gte: 2 },
      desc: 'Fast until your whole street gets home and starts downloading at once. Shared pipe, shared fate.',
      mods: [
        { key: 'hack.speed', mult: 1.3 },
        { key: 'trace', mult: 1.45 },
      ],
    },
    {
      id: 'net_fiber',
      name: 'Fiber Line',
      category: 'network',
      shop: 'computer',
      price: 200,
      tier: 5,
      upkeepPerDay: 3,
      available: { var: 'w.broadband', gte: 3 },
      desc: 'Glass to the door. So fast the bottleneck is you, blinking at a page that loaded before you finished pressing enter.',
      mods: [
        { key: 'hack.speed', mult: 1.4 },
        { key: 'trace', mult: 1.6 },
      ],
    },

    // ── Monitor ─────────────────────────────────────────────────────────────
    {
      id: 'crt_14in',
      name: '14" CRT',
      category: 'monitor',
      shop: 'computer',
      price: 0,
      tier: 0,
      unique: true,
      desc: 'Fourteen inches of warm, curved glass and a slight green tint. Degausses with a sound like a spring being murdered.',
      mods: [],
    },
    {
      id: 'crt_17in',
      name: '17" CRT',
      category: 'monitor',
      shop: 'computer',
      price: 180,
      tier: 1,
      desc: 'Three more inches and a flatter tube. Takes two people to lift and heats the room like a small sun.',
      mods: [
        { key: 'efficiency', mult: 1.02 },
        { key: 'stress.gain', mult: 0.98 },
      ],
    },
    {
      id: 'crt_19in',
      name: '19" Flat CRT',
      category: 'monitor',
      shop: 'computer',
      price: 260,
      tier: 2,
      desc: 'A genuinely flat screen, a crisp dot pitch, and a weight that voids most desk warranties. Worth it.',
      mods: [
        { key: 'efficiency', mult: 1.04 },
        { key: 'stress.gain', mult: 0.97 },
      ],
    },
    {
      id: 'monitor_lcd',
      name: '19" LCD Panel',
      category: 'monitor',
      shop: 'computer',
      price: 400,
      tier: 3,
      available: { day: true, gte: dayOf(2003, 0, 1) },
      desc: "Thin as a book, cool to the touch, and it doesn't buzz. You keep reaching behind it expecting a tube that isn't there.",
      mods: [
        { key: 'efficiency', mult: 1.08 },
        { key: 'stress.gain', mult: 0.95 },
      ],
    },
  ],
})
