/**
 * PKG-18 — street-level work: odd jobs, tech support, and the under-the-table track.
 *
 * Balance (CONTENT_GUIDE §6): odd jobs $25–40 for 4–6h; CompCastle bench $45; help desk $60.
 * Shady jobs are not scaled by `w.itSalary` (the engine only scales IT tracks) — cash is cash.
 */
import { dayOf } from '@/engine/calendar'
import { defineContent } from '@/engine/registry'
import type { JobDef } from '@/engine/types'
import { enrolledOrGrad } from './_shared'

const odd: JobDef[] = [
  {
    id: 'job_odd_paper_route',
    title: 'Morning Paper Route',
    employer: 'The Port Lumen Herald',
    track: 'odd',
    desc: 'Two hundred doorsteps across Cannery Row before the sun is up, a canvas bag that weighs as much as you do, and one dog on Pike Street who has sworn a blood oath against you personally. The pay is small. The mornings are beautiful, which nobody tells you.',
    pay: 26,
    shiftStart: 5,
    hours: 4,
    skillXp: { fitness: 4, social: 1 },
    stressPerHour: 0.6,
    energyPerHour: 4.5,
    maxLevel: 10,
    perk: 'Fresh air and exercise: a little mood every day.',
    mods: [{ key: 'mood.daily', add: 0.3 }],
  },
  {
    id: 'job_odd_flyers',
    title: 'Flyer Runner',
    employer: 'Sodium Row Print & Copy',
    track: 'odd',
    desc: 'Staple neon flyers to every telephone pole between the highway and the harbor: LAN parties, lost cats, a psychic who "also does taxes." Nobody checks whether you did it. You do it anyway, because you are that kind of person, and because the psychic called ahead.',
    pay: 25,
    shiftStart: 16,
    hours: 4,
    skillXp: { fitness: 2, social: 2 },
    stressPerHour: 0.6,
    energyPerHour: 4,
    maxLevel: 10,
    perk: 'You learn every pole, alley and shortcut on the Row.',
  },
  {
    id: 'job_odd_pizza_bike',
    title: 'Bike Courier',
    employer: 'Lumen Pizza Co.',
    track: 'odd',
    desc: 'Pizzas up the Hill on a bicycle with one working brake. The dorm kids tip in quarters and gratitude; the Harbor Point lawyers tip in exact change and contempt. Every box arrives hot, because you are fast, and because the brake is not a suggestion you can afford to test.',
    pay: 32,
    shiftStart: 18,
    hours: 5,
    skillXp: { fitness: 4, social: 1 },
    stressPerHour: 0.9,
    energyPerHour: 5,
    maxLevel: 10,
    perk: 'Staff pizza: the food budget stretches a little further.',
    mods: [{ key: 'expenses', mult: 0.95 }],
  },
  {
    id: 'job_odd_cathode',
    title: 'Counter & Dishes',
    employer: 'The Cathode Diner',
    track: 'odd',
    desc: 'Sal needs someone on the dish pit and the counter from dinner rush to the late crowd. The coffee is burnt, the pie is not, and every hard conversation on Sodium Row happens three stools away from you. Sal pays in cash, grilled cheese and unsolicited advice.',
    pay: 30,
    shiftStart: 17,
    hours: 5,
    skillXp: { social: 3, fitness: 1 },
    stressPerHour: 0.8,
    energyPerHour: 4,
    maxLevel: 12,
    req: { not: { var: 'w.cathode_open', eq: 0 } },
    visible: { not: { var: 'w.cathode_open', eq: 0 } },
    perk: 'Sal feeds you and listens: stress melts a little faster.',
    mods: [
      { key: 'stress.relief', mult: 1.08 },
      { key: 'expenses', mult: 0.95 },
    ],
  },
  {
    id: 'job_odd_library',
    title: 'Stacks Assistant',
    employer: 'Harbor Point Public Library',
    track: 'odd',
    desc: 'Reshelve, stamp, shush. The library has four public terminals, one of which is haunted by a screensaver nobody installed, and the reference desk will let you read anything you like on your break. Quiet work for people who like quiet.',
    pay: 28,
    shiftStart: 12,
    hours: 5,
    skillXp: { systems: 2, social: 1, business: 1 },
    stressPerHour: 0.6,
    energyPerHour: 3,
    maxLevel: 10,
    perk: 'Free run of the stacks: study goes a little further.',
    mods: [{ key: 'xp.all', mult: 1.04 }],
  },
  {
    id: 'job_odd_tv_cafe',
    title: 'Floor Attendant',
    employer: 'Terminal Velocity Cyber-Café',
    track: 'odd',
    desc: 'Twenty rented PCs, a coin-op espresso machine, and a sign that says NO GAMING AFTER 9 PM that everybody games under. You reset frozen machines, sell hour-cards, and pretend not to see what the scene kids in the back row are downloading. The owner used to be one of them. He pretends too.',
    pay: 36,
    shiftStart: 14,
    hours: 6,
    skillXp: { systems: 3, networking: 2, social: 1 },
    stressPerHour: 0.9,
    energyPerHour: 3.5,
    maxLevel: 12,
    req: { skill: 'systems', gte: 4 },
    perk: 'After-hours access to twenty machines and a fat pipe.',
    mods: [{ key: 'hack.speed', mult: 1.05 }],
  },
  {
    id: 'job_odd_pager_shop',
    title: 'Counter Clerk',
    employer: 'Beep City Pagers & Phones',
    track: 'odd',
    desc: 'Activate pagers, sell phone cards, and swap batteries on bricks the size of a sandwich. Beep City has been on Sodium Row since pagers were for doctors and drug dealers; now every fifteen-year-old wants one in translucent purple. You are the purple pager guy now. Embrace it.',
    pay: 38,
    shiftStart: 15,
    hours: 6,
    skillXp: { hardware: 3, social: 2, business: 1 },
    stressPerHour: 0.9,
    energyPerHour: 3.5,
    maxLevel: 12,
    req: { skill: 'hardware', gte: 5 },
    perk: 'Employee discount on gadgets and electronics.',
    mods: [{ key: 'expenses', mult: 0.97 }],
  },
]

const support: JobDef[] = [
  {
    id: 'job_compcastle_bench',
    title: 'Bench Technician',
    employer: 'CompCastle',
    track: 'support',
    desc: 'The service bench at the big blue box on the highway. Customers arrive clutching towers like wounded pets; you find the unplugged cable, the toolbar infestation, the cat hair. Dee runs the bench like a field hospital, and the first commandment is: we do not tell the customer the monitor was unplugged. We *heal* the customer.',
    pay: 45,
    shiftStart: 12,
    hours: 6,
    skillXp: { hardware: 4, systems: 3, social: 1 },
    stressPerHour: 1.1,
    energyPerHour: 3.8,
    maxLevel: 15,
    perk: 'Parts-bin access: dead machines donate their organs to yours.',
    mods: [{ key: 'efficiency', mult: 1.02 }],
  },
  {
    id: 'job_compcastle_lead',
    title: 'Service Bench Lead',
    employer: 'CompCastle',
    track: 'support',
    desc: 'You run the bench now: the schedule, the new kids, the warranty forms in triplicate, and the phone call where a man explains that his computer "just died" while it smells audibly of soda. The pay is better. The customers are exactly the same.',
    pay: 62,
    shiftStart: 11,
    hours: 7,
    skillXp: { hardware: 3, systems: 3, social: 2, business: 2 },
    stressPerHour: 1.3,
    energyPerHour: 3.8,
    maxLevel: 15,
    req: { all: [{ jobLevel: 'job_compcastle_bench', gte: 4 }, { skill: 'hardware', gte: 15 }, { skill: 'social', gte: 8 }] },
    perk: 'Keys to the storeroom: cheaper parts and first dibs on returns.',
    mods: [{ key: 'expenses', mult: 0.97 }],
  },
  {
    id: 'job_lsu_helpdesk',
    title: 'Campus IT Helper',
    employer: 'Lumen State University — Computing Services',
    track: 'support',
    desc: 'Student job in the Pell Hall basement: reset passwords, rescue term papers from floppies, and explain to a tenured professor that the "internet button" is a shortcut he deleted. The afternoon shift fits neatly after classes, and the work-study office pays on time.',
    pay: 52,
    shiftStart: 15,
    hours: 5,
    skillXp: { systems: 3, networking: 2, social: 2 },
    stressPerHour: 1.0,
    energyPerHour: 3.5,
    maxLevel: 12,
    req: { all: [enrolledOrGrad, { skill: 'systems', gte: 6 }] },
    visible: enrolledOrGrad,
    perk: 'Work-study: fits around the 10:00–14:00 class block.',
  },
  {
    id: 'job_northlink_helpdesk',
    title: 'Help Desk Technician',
    employer: 'NorthLink ISP',
    track: 'support',
    desc: 'A headset, a cubicle, and a queue of callers whose modems are "making the noise but not doing the internet." Evenings are the busiest: everyone gets home, dials in, and gets a busy signal. You will say "have you tried unplugging the phone cord for ten seconds" four hundred times a week, and some of those times it will work, and it will feel like magic.',
    pay: 60,
    shiftStart: 14,
    hours: 8,
    skillXp: { networking: 3, systems: 2, social: 2 },
    stressPerHour: 1.6,
    energyPerHour: 3.6,
    maxLevel: 15,
    req: { any: [{ skill: 'systems', gte: 10 }, { skill: 'networking', gte: 10 }] },
    perk: 'Free NorthLink account with a static line: downloads stop dying at 98%.',
    mods: [{ key: 'hack.speed', mult: 1.04 }],
  },
  {
    id: 'job_meridian_support',
    title: 'Online Banking Support Agent',
    employer: 'Meridian Trust Bank',
    track: 'support',
    desc: 'Meridian is dragging a hundred-year-old bank onto the web and needs people to answer the phone when customers discover the web is involved. Tie required. Customers call to ask whether the internet can see their money. You are trained to say "securely." You start to wonder.',
    pay: 75,
    shiftStart: 9,
    hours: 8,
    skillXp: { systems: 2, social: 3, business: 2 },
    stressPerHour: 1.4,
    energyPerHour: 3.4,
    maxLevel: 15,
    req: {
      all: [
        { day: true, gte: dayOf(2002, 2, 1) },
        { not: { flag: 'w.meridian_state', eq: 'collapsed' } },
        { skill: 'systems', gte: 15 },
        { skill: 'social', gte: 10 },
      ],
    },
    visible: { all: [{ day: true, gte: dayOf(2002, 2, 1) }, { not: { flag: 'w.meridian_state', eq: 'collapsed' } }] },
    perk: 'A bank tie and a bank badge: people take you more seriously.',
    mods: [{ key: 'check.social', add: 1 }],
  },
]

const shady: JobDef[] = [
  {
    id: 'job_shady_refurb',
    title: 'Refurb Tech (Back Room)',
    employer: 'Beep City — the room behind the curtain',
    track: 'shady',
    desc: 'Behind the bead curtain at Beep City, machines of uncertain origin get new cases, new serial stickers and new owners. You don\'t ask where they came from. The man who pays you asks you not to, very politely, every single shift.',
    pay: 55,
    shiftStart: 20,
    hours: 5,
    skillXp: { hardware: 5, systems: 2 },
    stressPerHour: 1.2,
    energyPerHour: 3.8,
    maxLevel: 12,
    req: { all: [{ skill: 'hardware', gte: 12 }, { stat: 'cred', gte: 5 }] },
    perk: 'Cash, no paperwork — and a faint smell of trouble that sticks to you.',
    mods: [{ key: 'heat.decay', add: -0.1 }],
  },
  {
    id: 'job_shady_verification',
    title: 'Data Verification Clerk',
    employer: 'Brightline Direct (an Aperture subsidiary)',
    track: 'shady',
    desc: 'A windowless call floor in Millgate where you "verify consumer records": you phone strangers, confirm their birthdays, and type what they say into a form that has far too many fields. The script is friendly. The headset is new. Nobody on the floor knows who the customer is, and the managers smile when you ask.',
    pay: 85,
    shiftStart: 10,
    hours: 8,
    skillXp: { social: 4, business: 2, opsec: 1 },
    stressPerHour: 1.5,
    energyPerHour: 3.4,
    maxLevel: 15,
    req: { all: [{ faction: 'fac.aperture', gte: 10 }, { skill: 'social', gte: 15 }, { flag: 'w.aperture_state', eq: 'thriving' }] },
    visible: { all: [{ flag: 'fac.aperture.client' }, { flag: 'w.aperture_state', eq: 'thriving' }] },
    perk: 'You hear how PARALLAX is fed — one friendly phone call at a time.',
    mods: [{ key: 'check.social', add: 1 }],
  },
  {
    id: 'job_shady_switch_crew',
    title: 'Crew Hand',
    employer: 'Switch\'s crew (the Loft, off the books)',
    track: 'shady',
    desc: 'Switch runs a paying crew out of the Sodium Row back room: setups, teardowns, fronting releases, fixing whatever the scene breaks. It is honest work in the sense that everybody is honest about how dishonest it is. Corvid pretends not to notice. Switch pays on Fridays, in an envelope, with a sticky note that says "commons don\'t pay rent."',
    pay: 70,
    shiftStart: 21,
    hours: 6,
    skillXp: { intrusion: 3, networking: 2, opsec: 2 },
    stressPerHour: 1.3,
    energyPerHour: 4,
    maxLevel: 15,
    req: { all: [{ faction: 'fac.loft', gte: 20 }, { npc: 'switch', met: true }, { skill: 'intrusion', gte: 12 }] },
    visible: { all: [{ faction: 'fac.loft', gte: 10 }, { npc: 'switch', met: true }] },
    perk: 'Scene contacts: contract work goes faster, and the Loft vouches for you.',
    mods: [
      { key: 'hack.speed', mult: 1.08 },
      { key: 'heat.decay', add: -0.15 },
    ],
  },
]

export default defineContent({ jobs: [...odd, ...support, ...shady] })
