/**
 * PKG-18 — the IT ladders: development, systems administration and network engineering.
 *
 * Balance (CONTENT_GUIDE §6): junior dev $90 · developer $140 · senior dev $210 · sysadmin $120 →
 * senior $200 · network engineer $170. Requirements climb skill 10 → 25 → 40 → 55 → 70 plus a
 * previous job level. Jobs flagged `job.offer.*` are "by invitation": the interview scenes in
 * `interviews.ts` set the flag.
 *
 * `job_halcyon_junior` is the Halcyon badge PKG-09's ladder is built around (it reads the job by
 * id): it carries the long Halcyon climb itself (max level 25), and the two senior Halcyon posts
 * require Halcyon Trusted so benefits and options are already settled when you move up.
 */
import { dayOf } from '@/engine/calendar'
import { defineContent } from '@/engine/registry'
import type { JobDef } from '@/engine/types'
import { enrolledOrGrad, halcyonAlive, meridianOpen } from './_shared'

const dev: JobDef[] = [
  {
    id: 'job_pixelworks_web',
    title: 'Web Developer',
    employer: 'Millgate Pixel Works (a four-person web shop)',
    track: 'dev',
    desc: 'Four people, one espresso machine, and a client list of dentists, realtors and one very intense ferry company. You build sites with spinning logos and visitor counters, and argue about whether anyone will ever need a site that works on a phone. (They will. Nobody believes you.)',
    pay: 70,
    shiftStart: 10,
    hours: 7,
    skillXp: { programming: 4, business: 1, social: 1 },
    stressPerHour: 1.1,
    energyPerHour: 3.5,
    maxLevel: 15,
    req: { skill: 'programming', gte: 10 },
    perk: 'Client overflow: your freelance gigs pay a little better.',
    mods: [{ key: 'freelance.pay', mult: 1.06 }],
  },
  {
    id: 'job_halcyon_junior',
    title: 'Junior Developer',
    employer: 'Halcyon Systems',
    track: 'dev',
    desc: 'The dot-com that survived the bust: exposed brick, a koi pond in the atrium, free soda and a CEO on the cover of Port Lumen Business Weekly. You write "project management for the connected enterprise," which is mostly forms, and ship on a schedule set by someone who has never shipped anything. The badge opens doors all over town.',
    pay: 90,
    shiftStart: 9,
    hours: 8,
    skillXp: { programming: 5, business: 2, social: 1 },
    stressPerHour: 1.4,
    energyPerHour: 3.6,
    maxLevel: 25,
    req: {
      all: [
        halcyonAlive,
        { skill: 'programming', gte: 20 },
        { any: [{ flag: 'fac.halcyon.employed' }, { faction: 'fac.halcyon', gte: 20 }, { degree: true }] },
      ],
    },
    perk: 'A Halcyon badge: +2 Halcyon rep per review (level), options, and in time, benefits.',
    mods: [{ key: 'efficiency', mult: 1.02 }],
  },
  {
    id: 'job_meridian_dev',
    title: 'Application Developer (Online Banking)',
    employer: 'Meridian Trust Bank',
    track: 'dev',
    desc: 'Meridian\'s online-banking team works on the fourteenth floor of the tower, where the carpet is thick and the code is not. The system is a new web face bolted onto a mainframe older than your parents, held together by a man named Gordon who is retiring in March. Nobody has asked what happens in April.',
    pay: 140,
    shiftStart: 9,
    hours: 8,
    skillXp: { programming: 4, systems: 3, business: 1 },
    stressPerHour: 1.5,
    energyPerHour: 3.5,
    maxLevel: 25,
    req: {
      all: [
        meridianOpen,
        { skill: 'programming', gte: 40 },
        { skill: 'systems', gte: 20 },
        { any: [{ jobLevel: 'job_halcyon_junior', gte: 5 }, { jobLevel: 'job_pixelworks_web', gte: 6 }, { jobLevel: 'job_meridian_support', gte: 5 }, { degree: true }] },
      ],
    },
    visible: { all: [meridianOpen, { skill: 'programming', gte: 30 }] },
    perk: 'You learn how the bank really works — from the inside of the vault door.',
    mods: [{ key: 'check.business', add: 1 }],
  },
  {
    id: 'job_coop_dev',
    title: 'Contract Developer',
    employer: 'Lumen Code Collective (freelance co-op)',
    track: 'dev',
    desc: 'A co-op of freelancers who rent a floor above a bakery in Millgate and split the overhead, the clients and the blame. You set your own late-morning hours, bill real rates, and vote on everything, including the brand of coffee, which has caused two schisms.',
    pay: 150,
    shiftStart: 11,
    hours: 6,
    skillXp: { programming: 5, business: 3 },
    stressPerHour: 1.0,
    energyPerHour: 3.3,
    maxLevel: 25,
    req: {
      all: [
        { skill: 'programming', gte: 45 },
        { skill: 'business', gte: 15 },
        { any: [{ jobLevel: 'job_pixelworks_web', gte: 5 }, { jobLevel: 'job_halcyon_junior', gte: 6 }, { jobLevel: 'job_meridian_dev', gte: 3 }, { var: 'sys.gigsDone', gte: 12 }] },
      ],
    },
    perk: 'Co-op rates and a shared client list: freelance pays and goes faster.',
    mods: [
      { key: 'freelance.pay', mult: 1.12 },
      { key: 'freelance.speed', mult: 1.08 },
    ],
  },
  {
    id: 'job_halcyon_senior',
    title: 'Senior Developer',
    employer: 'Halcyon Systems',
    track: 'dev',
    desc: 'A corner of the open-plan floor with a real chair, two monitors and a junior who thinks you are a wizard. You review code, estimate things that cannot be estimated, and sit in the Thursday meeting where Marcus Vale explains the future. Some weeks you believe him.',
    pay: 195,
    shiftStart: 9,
    hours: 9,
    skillXp: { programming: 5, business: 2, social: 2 },
    stressPerHour: 1.7,
    energyPerHour: 3.8,
    maxLevel: 25,
    req: {
      all: [
        halcyonAlive,
        { jobLevel: 'job_halcyon_junior', gte: 8 },
        { skill: 'programming', gte: 45 },
        { faction: 'fac.halcyon', gte: 50 },
      ],
    },
    perk: 'Seniority: job experience comes faster, and people wait for you in meetings.',
    mods: [{ key: 'jobXp', mult: 1.1 }],
  },
]

const sysadmin: JobDef[] = [
  {
    id: 'job_lsu_labtech',
    title: 'Lab Systems Technician',
    employer: 'Lumen State University — CS Department',
    track: 'sysadmin',
    desc: 'You keep the CS basement alive: forty lab machines, a humming server closet, and a research cluster whose grant paperwork nobody lets you read. Graduate students bring you cookies when their jobs finish. Professor Okoro brings you tea and questions.',
    pay: 75,
    shiftStart: 15,
    hours: 6,
    skillXp: { systems: 4, networking: 2, hardware: 1 },
    stressPerHour: 1.0,
    energyPerHour: 3.4,
    maxLevel: 15,
    req: { all: [enrolledOrGrad, { skill: 'systems', gte: 15 }] },
    visible: enrolledOrGrad,
    perk: 'After-hours lab access: study goes further.',
    mods: [{ key: 'xp.systems', mult: 1.1 }],
  },
  {
    id: 'job_northlink_noc_night',
    title: 'NOC Night Operator',
    employer: 'NorthLink ISP — Network Operations Center',
    track: 'sysadmin',
    desc: 'The graveyard shift in NorthLink\'s operations room: a wall of green lights, a phone that rings when one goes red, and eight hours of fluorescent quiet in which you can hear the building breathe. Night premium on the paycheck. Wes Tran leaves you a note every morning, usually about the coffee.',
    pay: 110,
    shiftStart: 22,
    hours: 8,
    skillXp: { systems: 3, networking: 4 },
    stressPerHour: 1.1,
    energyPerHour: 3.8,
    maxLevel: 20,
    req: {
      all: [
        { skill: 'systems', gte: 20 },
        { skill: 'networking', gte: 15 },
        { any: [{ jobLevel: 'job_northlink_helpdesk', gte: 3 }, { jobLevel: 'job_lsu_labtech', gte: 3 }, { skill: 'systems', gte: 30 }] },
      ],
    },
    perk: 'Night shift premium; days free for classes, the Row, or the terminal.',
  },
  {
    id: 'job_northlink_sysadmin',
    title: 'Systems Administrator',
    employer: 'NorthLink ISP',
    track: 'sysadmin',
    desc: 'The mail servers, the dial-up pools, the billing box that crashes on the first of every month, and the log archive that gets bigger every time a new memo comes down from legal. You keep all of it running. When it works, nobody knows your name. When it breaks, everybody does.',
    pay: 120,
    shiftStart: 9,
    hours: 8,
    skillXp: { systems: 5, networking: 2, opsec: 1 },
    stressPerHour: 1.5,
    energyPerHour: 3.6,
    maxLevel: 25,
    req: {
      all: [
        { skill: 'systems', gte: 30 },
        { skill: 'networking', gte: 20 },
        { any: [{ jobLevel: 'job_northlink_noc_night', gte: 3 }, { jobLevel: 'job_lsu_labtech', gte: 4 }, { jobLevel: 'job_northlink_helpdesk', gte: 5 }] },
      ],
    },
    perk: 'Root on the ISP: you see exactly what NorthLink keeps, and for how long.',
    mods: [{ key: 'trace', mult: 1.1 }],
  },
  {
    id: 'job_datacenter_ops',
    title: 'Data Campus Operations Tech',
    employer: 'Millgate Data Campus (the old paper mill)',
    track: 'sysadmin',
    desc: 'The paper mill is a server farm now. Where the pulp line ran there are rows of humming racks, badge readers on every door, and cold air that smells faintly, impossibly, of wet paper. Night crews swap drives and walk the aisles. The tenants\' names are on a list you are not cleared to read.',
    pay: 150,
    shiftStart: 22,
    hours: 10,
    skillXp: { systems: 4, hardware: 4, networking: 1 },
    stressPerHour: 1.4,
    energyPerHour: 4.2,
    maxLevel: 25,
    req: { all: [{ var: 'w.datacenter_open', eq: 1 }, { skill: 'systems', gte: 35 }, { skill: 'hardware', gte: 25 }] },
    visible: { var: 'w.datacenter_open', eq: 1 },
    perk: 'Long night shifts, big checks, and a badge into the heart of the machine.',
    mods: [{ key: 'pay', mult: 1.03 }],
  },
  {
    id: 'job_northlink_senior_sysadmin',
    title: 'Senior Systems Administrator',
    employer: 'NorthLink ISP',
    track: 'sysadmin',
    desc: 'You sign off on the maintenance windows, write the runbooks, and sit in the room when the lawyers explain what "retention" means this quarter. The junior admins call you when it is 3 a.m. and on fire. It is always 3 a.m. and on fire.',
    pay: 200,
    shiftStart: 9,
    hours: 8,
    skillXp: { systems: 5, networking: 2, business: 2 },
    stressPerHour: 1.8,
    energyPerHour: 3.6,
    maxLevel: 25,
    req: { all: [{ skill: 'systems', gte: 50 }, { jobLevel: 'job_northlink_sysadmin', gte: 6 }] },
    perk: 'Seniority and a pager: job experience comes faster.',
    mods: [
      { key: 'jobXp', mult: 1.1 },
      { key: 'trace', mult: 1.1 },
    ],
  },
]

const network: JobDef[] = [
  {
    id: 'job_northlink_field_tech',
    title: 'Broadband Field Installer',
    employer: 'NorthLink Broadband',
    track: 'network',
    desc: '"Always-on" is coming to Port Lumen one house at a time, and you are the one in the van. Crawlspaces, attics, a grandmother who insists on feeding you soup. You wire the whole city, one splitter at a time, and learn which streets the network forgot.',
    pay: 85,
    shiftStart: 8,
    hours: 8,
    skillXp: { networking: 4, hardware: 3, fitness: 1 },
    stressPerHour: 1.2,
    energyPerHour: 4.4,
    maxLevel: 20,
    req: { all: [{ var: 'w.broadband', gte: 1 }, { skill: 'networking', gte: 15 }, { skill: 'hardware', gte: 10 }] },
    visible: { var: 'w.broadband', gte: 1 },
    perk: 'Company van and a free install: your own line gets the good hardware.',
    mods: [{ key: 'hack.speed', mult: 1.05 }],
  },
  {
    id: 'job_northlink_neteng',
    title: 'Network Engineer',
    employer: 'NorthLink ISP',
    track: 'network',
    desc: 'You design where the city\'s traffic goes: the backbone, the peering links, the rack in the mill district that is suddenly the most important room in Port Lumen. By invitation only; NorthLink doesn\'t advertise this chair. You get the chair if Wes vouches for you.',
    pay: 170,
    shiftStart: 9,
    hours: 8,
    skillXp: { networking: 5, systems: 2, business: 1 },
    stressPerHour: 1.6,
    energyPerHour: 3.5,
    maxLevel: 25,
    req: {
      all: [
        { skill: 'networking', gte: 40 },
        { flag: 'job.offer.northlink_neteng' },
        { any: [{ jobLevel: 'job_northlink_sysadmin', gte: 4 }, { jobLevel: 'job_northlink_field_tech', gte: 5 }, { jobLevel: 'job_northlink_noc_night', gte: 5 }] },
      ],
    },
    visible: { skill: 'networking', gte: 30 },
    perk: 'You know every route in the city: traces run slower against you.',
    mods: [{ key: 'trace', mult: 1.2 }],
  },
  {
    id: 'job_northlink_architect',
    title: 'Senior Network Architect',
    employer: 'NorthLink ISP',
    track: 'network',
    desc: 'The whole map is yours: fiber rings under the Sound, the new trunk through the old copper exchange, the plans that say where Port Lumen\'s traffic will flow for the next twenty years. Vendors send you fruit baskets. One of them is from a company in Millgate that nobody at NorthLink will talk about.',
    pay: 260,
    shiftStart: 9,
    hours: 8,
    skillXp: { networking: 5, business: 2, systems: 2 },
    stressPerHour: 1.7,
    energyPerHour: 3.4,
    maxLevel: 25,
    req: { all: [{ skill: 'networking', gte: 60 }, { jobLevel: 'job_northlink_neteng', gte: 6 }, { day: true, gte: dayOf(2005, 0, 1) }] },
    perk: 'The map in your head: traces crawl, and hacking goes faster.',
    mods: [
      { key: 'trace', mult: 1.3 },
      { key: 'hack.speed', mult: 1.05 },
    ],
  },
]

export default defineContent({ jobs: [...dev, ...sysadmin, ...network] })
